### ISSUE TITLE
hub issue behavior

### ISSUE THREAD

**Issue by digitalnoise** [github/hub#1872] opened 2018-09-12 20:49 UTC
`hub issue` on a forked repo lists all issues on the upstream master, instead of the locally forked repo.

**Comment by mislav** [comment] 2018-09-13 12:16
Yes this is intended behavior. Have you expected otherwise? If hub's behavior was different here, how would people access the list of issues on the upstream repo?

**Comment by digitalnoise** [comment] 2018-09-13 14:44
But how would people access the list of issues on the fork itself?  Projects are forked for various reasons, and changes to a specific fork could create issues specific to that fork, but hub doesn't offer any way to access those issues - only on the upstream.

**Comment by mislav** [comment] 2018-09-14 08:14
That's true, hub doesn't offer any way to access issues on other repos. That's why a flag such as `--remote` could solve this problem. Closing in favor of #1342

**Closed by mislav** 2018-09-14 08:14 UTC
