### ISSUE TITLE
Feature request: Search my own repositories on GitHub

### ISSUE THREAD

**Issue by yousan** [github/hub#1925] opened 2018-10-30 16:20 UTC
Hi.

# Requested Changes
Add `hub search <keyword>` command to search repos that I have permissions.

```
$ hub search hub
https://github.com/github/hub/
```

```
$ hub search --ssh hub
git@github.com:github/hub.git
```

Then I can easy to clone repos into local.

```
$ git clone $(hub search hub)
```

Thanks.

**Comment by mislav** [comment] 2018-10-30 21:07
That's a good idea!

Closing as duplicate of #833

**Closed by mislav** 2018-10-30 21:07 UTC
