### ISSUE TITLE
Getting an error when trying to set milestone

### ISSUE THREAD

**Issue by materik** [github/hub#1089] opened 2016-01-25 15:50 UTC
``` bash
$ hub pull-request -M "3.12"
invalid argument "3.12" for -M: strconv.ParseUint: parsing "3.12": invalid syntax
usage: git pull-request [-f] [-m <MESSAGE>|-F <FILE>|-i <ISSUE>|<ISSUE-URL>] [-o] [-b <BASE>] [-h <HEAD>] [-a <USER>] [-M <MILESTONE>] [-l <LABELS>]
...
$ hub --version
git version 2.5.4 (Apple Git-61)
hub version 2.2.0-124-gd0ad43d
```

**Comment by skat00sh** [comment] 2016-01-25 17:40
I'm new to github contribution & I would like to work on this bug.

**Comment by mislav** [comment] 2016-01-25 23:44
@materik Right now we only support assigning a milestone ID as an argument. That makes the feature a little bit useless, I admit, since you need to first use the API manually to retrieve the milestone ID.

This functionality hasn't been released as a stable release yet, though, which gives us an opportunity to correct that.

@skat00sh It would be great if you fixed this. [Here's where milestone assignment](https://github.com/github/hub/blob/35905f710a0e7eb29f102d9ded28995f278ce5d2/commands/pull_request.go#L236-L242) happens. Instead of accepting an integer argument that represents a milestone ID, we should accept a string argument that represents a milestone name.

We should use the API to look up available milestones by name to map it to an ID. Here's an example of [how to do API requests](https://github.com/github/hub/blob/35905f710a0e7eb29f102d9ded28995f278ce5d2/github/client.go#L338-L368).

**Comment by materik** [comment] 2016-01-26 15:40
:+1:

**Comment by jingweno** [comment] 2016-01-28 23:41
> Right now we only support assigning a milestone ID as an argument. That makes the feature a little bit useless, I admit, since you need to first use the API manually to retrieve the milestone ID.

:+1:

**Comment by skat00sh** [comment] 2016-01-29 13:27
@mislav  Sorry for reverting so late! 
If the issue is still open. I would like to ask, as per [this: milestone assignment](https://github.com/github/hub/blob/35905f710a0e7eb29f102d9ded28995f278ce5d2/commands/pull_request.go#L236-L242) I think changing the datatype of milestone (from int to string) would be a start.
Some how I could not understand what to do at the API end, as per you referred [here: how to do API requests.](https://github.com/github/hub/blob/35905f710a0e7eb29f102d9ded28995f278ce5d2/github/client.go#L338-L368).

**Comment by mislav** [comment] 2016-01-30 05:49
> Some how I could not understand what to do at the API end,

Yes, changing the milestone from int to string would be a start. Next, you would have to fetch all open milestones via API and extract the milestone ID whose name matches the milestone name string provided by the user. Then, feed the milestone ID into the original call to update the PR.

I've linked you the example of how API requests are done, but I can't help you much more than that. If this seems more than you can handle at first, that's OK. Let me know and I can take it from here.

**Comment by venyii** [comment] 2018-01-23 13:48
Hi there, is this still planned? I used this flag for the first time today and really wished it used the milestone name 😄 I'd like to give it a shot if it's still intended to work as described above.

Let me know, thanks!

**Closed** 2018-04-06 09:36 UTC
Labels: feature
