### ISSUE TITLE
2.2.0-2.2.2: GitHub Enterprise is unusable with hub

### ISSUE THREAD

**Issue by davidburstromspotify** [github/hub#1045] opened 2015-12-04 16:22 UTC
Since at least 2.2.0, it's no longer possible to use an enterprise GitHub installation.
The configuration
  [hub]
    host = ghe.mycompany.com

does nothing. When invoking

  hub pull-request -b master

you get the error message

  Aborted: the origin remote doesn't point to a GitHub repository.

**Comment by mislav** [comment] 2015-12-05 18:01
Ouch, I'm sorry that you're having trouble. Hub should definitely still work with Enterprise.

What is your exact `hub version`? Thanks

**Comment by davidburstromspotify** [comment] 2015-12-05 18:38
I've tried both with brew version 2.2.0 and with 2.2.2 Mac installation,
both broken.

:-David

**Comment by mislav** [comment] 2015-12-06 17:13
From your project's directory:

1. What is your `git remote -v`? You can anonymize hostnames if necessary.
2. What is `git config --get-all hub.host` from your project's directory?

Thanks

**Comment by davidburstromspotify** [comment] 2015-12-06 18:16
$ git remote -v
origin git@ghe.ourdomain.net:username/repo.git (fetch)
origin git@ghe.ourdomain.net:username/repo.git (push)
upstream git@ghe.ourdomain.net:upstream/repo.git (fetch)
upstream no_push (push)
$ git config --get-all hub.host
ghe.ourdomain.net
ghe.ourdomain.net

It's listed twice because it's in the global config as well as the project
config, but removing either of them doesn't make any difference, still
getting "Aborted: the origin remote doesn't point to a GitHub repository."

**Comment by mislav** [comment] 2015-12-06 19:36
Thanks for that info. The problem is that it's picking up `no_push` from "upstream" remote configuration and failing. We're aware of the issue and it will be fixed in the next release.

However, it's still going to pick the repository from "upstream" remote (`upstream/repo` in your case) to open PRs against. Does that match your expectations?

**Comment by davidburstromspotify** [comment] 2015-12-06 19:49
Aha, good news then. Yes, it matches my expectation. On a side note, it is
strange that it mentions "origin" instead of "upstream" in the error
message.

**Comment by mislav** [comment] 2016-01-20 09:11
This was fixed in #1025 and will be released as part of the next bugfix release.

**Closed by mislav** 2016-01-20 09:11 UTC
Labels: unconfirmed
