### ISSUE TITLE
Crash report - runtime error: index out of range (`git create` after `git init --bare`)

### ISSUE THREAD

**Issue by sleexyz** [github/hub#1431] opened 2017-03-08 06:13 UTC
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x780ca0, 0xc420010140)
	/nix/store/6s9ipd2x4zm8nk5ml7dfdvibq2azg8x9-go-1.7.4/share/go/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc4200e81e0, 0x1c, 0x0, 0x0)
	/tmp/nix-build-hub-2.2.9.drv-0/go/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x9a65e0, 0xc4200230e0)
	/tmp/nix-build-hub-2.2.9.drv-0/go/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x9a65e0, 0xc4200230e0, 0x7fff343fecf6, 0x6)
	/tmp/nix-build-hub-2.2.9.drv-0/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420011710, 0x9a65e0, 0xc4200230e0, 0x6, 0xc420083d68, 0xc42005fed8, 0x401039)
	/tmp/nix-build-hub-2.2.9.drv-0/go/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc420011710, 0x814970, 0x47dabe, 0xc42001c180, 0x0)
	/tmp/nix-build-hub-2.2.9.drv-0/go/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/tmp/nix-build-hub-2.2.9.drv-0/hub/main.go:14 +0x51

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.11.1
hub version 2.2.9
```

**Comment by mislav** [comment] 2017-06-26 15:42
Thanks for reporting! Duplicate of https://github.com/github/hub/issues/1331

**Closed by mislav** 2017-06-26 15:42 UTC
