### ISSUE TITLE
Does not work with private organization repos

### ISSUE THREAD

**Issue by fatso83** [github/hub#1075] opened 2016-01-13 14:17 UTC
Neither issue listing, pull requests nor browsing works as intended when used in conjunction with organization repos.

```
#all commands performed in a git repo

$ hub issue
Error getting issues: Not Found (HTTP 404)
Not Found

$ hub pull-request -h jira-1320
Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/fatso83/MYORG exists?

hub browse # opens https://github.com/fatso83/MYORG, not /MYORG/REPO_NAME

# installed through Homebrew
$ hub version
git version 2.5.4 (Apple Git-61)
hub version 2.2.1
```

Using ssh based transports, not http.

**Comment by mislav** [comment] 2016-01-20 08:50
Thanks for reporting! First of all, the latest release is 2.2.2, so make sure you're testing with that.

Second, we'll need more information. What is the `git remote -v` configuration? Where was `jira-1320` pushed? Is there any upstream tracking set up? What is the value of `git config push.default`?

Third, the `hub issue` command is still in beta and shouldn't be considered final. But the other commands should work.

**Comment by fatso83** [comment] 2016-01-20 12:29
Hmm ... after examining some more it seems that it depends on the repo. In one repo that is tracking an organization repo the above command fails, in the other it works. Both use SSH transports, and  seem to be configured pretty much the same. 

I will have to look some more into it to get more details.

**Comment by mislav** [comment] 2016-01-20 12:40
@fatso83 Might it be a repo that's been renamed but still keeps its old name in git remotes urls?

**Comment by fatso83** [comment] 2016-01-21 11:13
Found the issue. My remote has a forward slash in the address. My guess is that it has to do with the way hub resolves/rewrites the ssh transports into equivalent https addresses. I believe this is a bug as `git` (or GitHub?) resolves the address just fine, while hub does not.

Fix for issue:
```
$ git config  --get remote.origin.url
git@github.com:/MYORG/my-repo

$ git config  --unset remote.origin.url

$ git config --add remote.origin.url git@github.com:MYORG/my-repo

$ git issue
    116] Detect localstorage availability ( https://github.com/MYORG/my-repo/pull/116 )
    103] Githooks for post-commit ( https://github.com/MYORG/my-repo/issues/103 )
     78] Clean up network layer ( https://github.com/MYORG/my-repo/issues/78 )
```

_hub version 2.2.2_

**Comment by mislav** [comment] 2016-01-21 13:42
Thanks for looking into this! Duplicate of #876

**Closed by mislav** 2016-01-21 13:42 UTC
Labels: unconfirmed
