### ISSUE TITLE
Unable to use with GitHub Enterprise

### ISSUE THREAD

**Issue by hallem** [github/hub#952] opened 2015-07-08 20:35 UTC
I'm using hub with GHE and have the host and protocol set in the global git config.  But when I run the "hub pull-request" command I get the following:

Aborted: the origin remote doesn't point to a GitHub repository.

**Comment by mislav** [comment] 2015-07-09 05:12
What's your `git config --get-all hub.host`?

**Comment by hallem** [comment] 2015-07-09 23:53
$ git config --get-all hub.host
https://github.***.com

**Comment by hallem** [comment] 2015-07-09 23:56
I also have this set:

$ git config --get-all hub.protocol
https

**Comment by mislav** [comment] 2015-07-10 04:53
And does the origin remote point to `github.whatever.com`? Check with `git remote -v`

**Comment by hallem** [comment] 2015-07-11 18:23
yes it does.  i do have two remotes though, origin points to that and upstream to something else.

**Comment by hallem** [comment] 2015-07-19 03:45
@mislav any ideas?

**Comment by mislav** [comment] 2015-07-20 18:03
Sorry for the late follow-up. If "upstream" remote is pointing to a non-GitHub instance, that might be what's tripping it up, because hub will prefer "upstream" remote over "origin" (this was an often-requested feature before). As a workaround you might want to consider renaming the "upstream" remote to something else, or specifying the pull-request base directly:

```
hub pull-request -b "<gh-username>:<branch-name>"
```

**Comment by hallem** [comment] 2015-07-21 00:04
upstream also points to a non-github instance but it's the same GHE instance just a different fork.  i can try calling it something else and see how that works. more to follow.

**Comment by mislav** [comment] 2015-07-21 01:01
Well, when I said "non-github instance" I meant a server that's not any version of GitHub, including GHE.

I don't know where the problem lies. The error message is certainly faulty, since both remotes point to some version of GitHub.

**Comment by dlenski** [comment] 2015-07-22 22:26
@hallem, is it possible that the explicit `https://` prefix in your [example](//github.com/github/hub/issues/952#issuecomment-120177068) is the problem?

(On my system it's just `github.**.com` with no prefix, and `hub clone` works fine.)

**Comment by kevinSuttle** [comment] 2015-07-23 01:55
Could be private mode https://help.github.com/enterprise/2.0/admin/articles/private-mode/

**Comment by mislav** [comment] 2015-07-23 15:04
I think @dlenski is right. Sorry for not catching that before.

**Comment by mislav** [comment] 2015-09-27 18:04
Closing because I think the issue is what @dlenski described. The list in `git config --get-all hub.host` should be just hostnames without the protocol. Try that and please reopen if the issue persists.

**Closed by mislav** 2015-09-27 18:04 UTC
