### ISSUE TITLE
hub browse should directly open the pull request page

### ISSUE THREAD

**Issue by dufferzafar** [github/hub#1107] opened 2016-02-08 16:03 UTC
I am not sure if this is too far fetched or if it's even possible. So please bear with me :smile_cat: 

If I am on a feature branch that has an existing pull request on Github and I do a `hub browse`, I just want it to open the pull request page rather than the repository page.

So, let's say I am on branch `cool-feature`, and it is associated to pull request 90, then browse should just open `github.com/:user/:repo/pulls/90`

**Comment by mislav** [comment] 2016-02-09 01:11
That's an interesting suggestion. I definitely see a value in that feature, but what if a person expected to simply open the current branch online and didn't appreciate that this behavior will differ based on whether the current branch has a PR or not?

**Comment by dufferzafar** [comment] 2016-02-09 12:06
@mislav Um, we provide switches to handle the use cases?

**Comment by mislav** [comment] 2016-02-09 21:47
> we provide switches to handle the use cases?

That's an option of course. How would the switches look like?

**Comment by dufferzafar** [comment] 2016-02-10 07:45
If you want the default behavior of `hub browse` to stay unchanged, we could provide switches like `-p` for opening up the linked pull request, `-b` for the branch etc.

**Comment by pcorpet** [comment] 2016-02-13 18:22
This is a pretty easy follow up to #1109 . @mislav Assign it to me if you wish.

**Comment by dufferzafar** [comment] 2016-09-29 15:12
I needed this feature again today. Are there any plans on working on it? since people seem to agree with the feature request.

**Comment by mislav** [comment] 2016-09-29 16:28
@dufferzafar Nobody is working on this yet, afaik. It's up for grabs!

**Comment by dufferzafar** [comment] 2016-09-29 16:43
@mislav Okay. I might work on this, but I'm new to the project. Can you please tell where I'd start working on this? I saw PR #1109 being mentioned above but I had a look at it, and was quite overwhelmed by the level of discussion there. Just knowing which files I'd need to look into etc. would be a great help!

**Comment by mislav** [comment] 2016-09-30 17:21
@dufferzafar It can be tricky to navigate your way around a new codebase, but you shouldn't let it deter you.

Code-wise, you could definitely start at `browse.go`, see how that's implemented, and try to squeeze in a new option flag. But I wouldn't recommend it, since `browse` command is already too overloaded and messy and I'd like to make a new command to replace it.

So I'd rather start a new subcommand `hub open` and make it open a pull request page if the current branch corresponds to one. Then later we can extend the new command with abilities to browse other branches, commits, tags, and so on.

**Comment by mislav** [comment] 2017-06-26 09:44
I don't think we will be changing the `browse` command to add this feature (or any other features, for that matter), and instead we might deprecate it in favor of the upcoming `hub open` command that takes slightly different arguments.

A separate command to open an existing pull request should definitely exist, because I agree that it would be useful. Closing this as duplicate of #897

**Closed by mislav** 2017-06-26 09:44 UTC
Labels: feature

**Comment by arfilmsphotography** [comment] 2022-12-20 14:52
> I am not sure if this is too far fetched or if it's even possible. So please bear with me 😸
> 
> If I am on a feature branch that has an existing pull request on Github and I do a `hub browse`, I just want it to open the pull request page rather than the repository page.
> 
> So, let's say I am on branch `cool-feature`, and it is associated to pull request 90, then browse should just open `github.com/:user/:repo/pulls/90`
