### ISSUE TITLE
`hub pull-request` command with no options bahavior for base hand head

### ISSUE THREAD

**Issue by wkentaro** [github/hub#1006] opened 2015-10-04 21:42 UTC
**Latest hub**
```
% git remote -v
origin	https://github.com/jsk-ros-pkg/jsk_common.git (fetch)
origin	https://github.com/jsk-ros-pkg/jsk_common.git (push)
wkentaro	git@github.com:wkentaro/jsk_common.git (fetch)
wkentaro	git@github.com:wkentaro/jsk_common.git (push)

% git branch -a
  doc-for-jsk-data-cli
  interactive-jsk-data
  master
* test-branch
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/wkentaro/add-jade-test
  remotes/wkentaro/doc-for-jsk-data-cli
  remotes/wkentaro/interactive-jsk-data
  remotes/wkentaro/master
  remotes/wkentaro/ros-info-warn-no-connect
  remotes/wkentaro/test-branch

% git push wkentaro test-branch
Everything up-to-date

% hub --version
git version 1.9.1
hub version 2.2.1

% hub pull-request
```

The editor opens:
```
# Requesting a pull to jsk-ros-pkg:master from jsk-ros-pkg:test-branch
#
# Write a message for this pull request. The first block
# of text is the title and the rest is description.
```

**Old hub**
```
% hub --version
git version 1.9.1
hub version 1.12.4

% hub pull-request
```

I had:

```

# Requesting a pull to jsk-ros-pkg:master from wkentaro:test-branch
#
# Write a message for this pull request. The first block
# of text is the title and the rest is description.
#
# Changes:
#
# 06c8ee9 (Kentaro Wada, 6 hours ago)
#    [jsk_data] Refactor: add cmd_pubinfo to __all__
#
# e37b75f (Kentaro Wada, 8 hours ago)
#    [jsk_data] Select filename with percol in pubinfo
#
# 96df8ee (Kentaro Wada, 8 hours ago)
#    [jsk_tools] Commandline tool for selection with percol
```

the latter behavior is what I expected.

So, the behavior of `hub pull-request` was changed after upgraded?

**Comment by mislav** [comment] 2015-10-04 22:21
Thanks for all the debugging info. This is certainly a bug in the newer version and I'll work on getting this fixed.

Closing as duplicate of #928

**Closed by mislav** 2015-10-04 22:21 UTC
