### ISSUE TITLE
Obtain github token from a command

### ISSUE THREAD

**Issue by rcorre** [github/hub#2542] opened 2020-05-15 18:39 UTC
**The problem I'm trying to solve:**

I'd like a more secure way to store my token for `hub`. I already use [pass](https://www.passwordstore.org/) to store my credentials, all I need is a way to invoke it from hub.
Technically right now I could `alias hub="GITHUB_TOKEN=$(pass hub) hub"`, but it would be preferable to not have my token in the env at all.

**How I imagine hub could expose this functionality:**

```
git config --global hub.tokencmd = "pass hub"
```

If a token is not set in the hub config file _or_ the environment, `hub` will attempt to invoke `hub.tokencmd` and use the `stdout` as your token. `hub` will _not_ store the result of this -- it will invoke the command every time it needs a token.

I'm happy to implement this if there is an interest. This relates to https://github.com/github/hub/issues/463:

> Yes I would be open to PRs that improve security, but in a way that potentially helps the majority of hub users and across different platforms.

I think this satisfies all of those requests. If someone wants to use `gpg`, they can set `hub.tokencmd="gpg -d hub.gpg"` and get that functionality without `hub` having to implement anything specific for gpg.

**Comment by mislav** [comment] 2020-05-25 22:18
Thanks! Going to mark this as a duplicate of https://github.com/github/hub/issues/1217

I plan to support reading from a credentials cache command, but the command will likely be configurable so you can use `pass` as well.

**Closed by mislav** 2020-05-25 22:18 UTC
Labels: feature
