### ISSUE TITLE
branch has no history in common with master

### ISSUE THREAD

**Issue by syedafirdaus** [github/hub#2322] opened 2019-10-22 13:17 UTC
command used 
hub pull-request -m title -h {user}:{branch}
When i do above pull request from shell, i get below error

Error creating pull request: Unprocessable Entity (HTTP 422)
The {mybranch} branch has no history in common with master

Please advise

**Comment by mislav** [comment] 2019-10-22 14:57
Thanks for reporting. This is an error you got from GitHub API (evident by the HTTP 422 error), not from hub. GitHub is for some reason convinced that `{branch}` does not have anything in common with `master` (in git, this is possible).

Check if you can open the PR from the web UI: `hub browse -- compare/{user}:{branch}` (fill in the `{...}` with your values). If you get the same error, then you can't open a PR from `{branch}`. If you are convinced that `{branch}` and `master` do in fact have histories in common, then please write to https://github.com/contact about this and provide them enough details so that they can debug.

For now I'm closing this because it's not a bug with hub. Thank you!

**Closed by mislav** 2019-10-22 14:57 UTC
