### ISSUE TITLE
hub browse is not working

### ISSUE THREAD

**Issue by ayushgoel** [github/hub#1565] opened 2017-09-08 12:12 UTC
Unable to use `hub browse`.

```
$ hub --version
git version 2.14.1
hub version 2.2.9
$ hub browse
Unterminated backslash-escape
```

**Comment by e-beach** [comment] 2017-09-08 14:33
@ayushgoel Does that happen when you run
```
git clone hub
cd hub
hub browse
```
Or is it specific to a repository?

**Comment by ayushgoel** [comment] 2017-09-08 15:55
It happens on all the repositories, whether they be public or private.

**Comment by e-beach** [comment] 2017-09-18 15:36
If you're interested, let me try to reproduce this issue. What Linux distro are you running?

**Comment by ayushgoel** [comment] 2017-09-18 15:39
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

Let me know in case you need anymore info.

**Comment by e-beach** [comment] 2017-09-20 02:34
Can I also get your `gitconfig`?

**Comment by GavinHuang0913** [comment] 2017-09-20 03:29
Hi Elliott

OK.
But i don't know how to let u get my gitconfig?

best regards
Gavin

**Comment by e-beach** [comment] 2017-09-20 03:32
@GavinHuang0913 are you @ayushgoel??? I'm confused.

**Comment by GavinHuang0913** [comment] 2017-09-20 03:35
I am not @ayushgoel ....Sorry.

**Comment by ayushgoel** [comment] 2017-09-20 06:14
Hello @e-beach ,

I have no clue how, but `hub browse` has started working again for me. No version has changed, so I am still using the same configuration as before.

```bash
$ hub --version
git version 2.14.1
hub version 2.2.9
```

This is my gitconfig (currently), in case it is useful..

```bash
[user]
	name = Ayush Goel
	email = ayush*******@gmail.com
[color]
    branch = auto
    diff = auto
    status = auto
    ui = always
[merge]
    tool = opendiff
[pager]
    status = true
[core]
	excludesfile = /Users/ayushgoel/.gitignore_global
[credential]
    helper = osxkeychain
[push]
    default = simple
[diff "xcdatamodel"]
    xfuncname = ^Entity.*$
    textconv = XCDataModelPrinter
[diff "plist"]
    textconv = plutil -convert xml1 -o -

#driver for merging Xcode project files
[merge "mergepbx"]
        name = Xcode project files merger
        driver = mergepbx %O %A %B
[rerere]
    enabled = true
[difftool "sourcetree"]
	cmd = opendiff \"$LOCAL\" \"$REMOTE\"
	path = 
[mergetool "sourcetree"]
	cmd = /Applications/SourceTree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
	trustExitCode = true
[commit]
	template = /Users/ayushgoel/.stCommitMsg
```

**Comment by mislav** [comment] 2017-09-20 13:21
@ayushgoel If there is no problem anymore, you can close this. If it comes back, please use HUB_VERBOSE to get more detail, as helpfully suggested by @e-beach.

**Comment by tanduong** [comment] 2017-10-11 08:20
I am having this issue. `hub browse` has never work for me. Here is my output:

```
git:(master) HUB_VERBOSE=true git browse
$ git config alias.browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/master
Unterminated backslash-escape
```

**Comment by mislav** [comment] 2017-10-13 18:13
@tanduong Is your issue reproducible every time? Does it matter which directory are you currently in, or does it happen in every project? Can you help us reproduce this by giving us more information about your hub version and your operating system? Thank you!

**Comment by mislav** [comment] 2018-05-29 13:27
Closing this due to lack of information.

**Closed by mislav** 2018-05-29 13:27 UTC

**Comment by ayushgoel** [comment] 2018-07-10 10:55
```sh
$ env HUB_VERBOSE=true hub browse
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
$ git config push.default
$ git rev-parse -q --git-path refs/remotes/origin/use-frameworks
Unterminated backslash-escape
```
