### ISSUE TITLE
hub pr list should allow you to show all merged Pull Requests since <date>

### ISSUE THREAD

**Issue by timgws** [github/hub#2186] opened 2019-07-09 02:01 UTC
It would be very nice if you could get a list of all the merged pull requests since a given date.

This would make generating change logs very easy!

**Comment by mislav** [comment] 2019-07-09 22:30
For sure, that would be useful! Duplicate of https://github.com/github/hub/issues/2085

**Closed by mislav** 2019-07-09 22:30 UTC
