### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by DylanGraham** [github/hub#1480] opened 2017-05-18 05:48 UTC
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x77bb20, 0xc420010190)
	/usr/lib/golang/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc4200dcde0, 0x24, 0x0, 0x0)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x99a4a0, 0xc42008ee60)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x99a4a0, 0xc42008ee60, 0x7fff7a5d03be, 0x6)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420011580, 0x99a4a0, 0xc42008ee60, 0x6, 0xc42007de30, 0xc420061ed8, 0x401039)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc420011580, 0x80f1e8, 0x47da9e, 0xc4200d80c0, 0x0)
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/builddir/build/BUILD/hub-80948b0688966a8f512820f869b4ec3237b7822e/src/github.com/github/hub/main.go:14 +0x51

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.9.4
hub version 2.2.9
```

**Comment by mislav** [comment] 2017-06-26 15:43
Thanks for reporting! Duplicate of https://github.com/github/hub/issues/1331

**Closed by mislav** 2017-06-26 15:43 UTC
