### ISSUE TITLE
Open a pull request with the last commit message like the web interface

### ISSUE THREAD

**Issue by danielnolan** [github/hub#847] opened 2015-03-19 00:45 UTC
When on a topic branch with only one commit and running `hub pull-request` my editor opens with this text.

![screen shot 2015-03-18 at 8 41 50 pm](https://cloud.githubusercontent.com/assets/635285/6722384/423c005a-cdaf-11e4-9074-ef7c798168a1.png)

Doesn't hub use the last commit message for the pull-request title and description if there is only one commit?

**Comment by mislav** [comment] 2015-03-19 03:40
Yes, it should. What is your `git log master..dan-modify-zshrc`?

**Comment by danielnolan** [comment] 2015-03-19 04:34
![screen shot 2015-03-19 at 12 33 48 am](https://cloud.githubusercontent.com/assets/635285/6724507/bf2894d2-cdcf-11e4-96ce-dcb44b5fb2e7.png)

**Comment by mislav** [comment] 2015-03-19 17:41
Strange! Which version of hub?

**Comment by danielnolan** [comment] 2015-03-20 00:04
2.2.0

**Comment by mislav** [comment] 2015-03-23 23:36
What is your upstream configuration?

* `git remote -v`
* `grep branch -A3 .git/config`
* `git config push.default`

**Comment by untitaker** [comment] 2015-04-10 16:19
I think this is related to my problem: `hub` "leaks" the previous PR message into the new one. This happens on a per-repo basis (obviously, given where hub stores its tempfile).

    $ hub --version
    git version 2.3.5
    hub version 2.2.0

    $ git remote -v
    geier   git://github.com/geier/vdirsyncer.git (fetch)
    geier   git://github.com/geier/vdirsyncer.git (push)
    michaeladler    git://github.com/michaeladler/vdirsyncer.git (fetch)
    michaeladler    git://github.com/michaeladler/vdirsyncer.git (push)
    origin  git@github.com:untitaker/vdirsyncer.git (fetch)
    origin  git@github.com:untitaker/vdirsyncer.git (push)
    t-8ch   git://github.com/t-8ch/vdirsyncer.git (fetch)
    t-8ch   git://github.com/t-8ch/vdirsyncer.git (push)

    $ grep branch -A3 .git/config
    [branch "master"]
            remote = origin
            merge = refs/heads/master
    [remote "t-8ch"]
    --
    [branch "tls_fingerprints"]
            remote = origin
            merge = refs/heads/tls_fingerprints
    [branch "more_multi_methods"]
            remote = origin
            merge = refs/heads/more_multi_methods
    [remote "michaeladler"]
    --
    [branch "sync_rewrite"]
            remote = origin
            merge = refs/heads/sync_rewrite
    [branch "fingerprint-adapt"]
            remote = origin
            merge = refs/heads/fingerprint-adapt

    $ git config push.default
    tracking

**Comment by mislav** [comment] 2015-04-13 14:26
> hub "leaks" the previous PR message into the new one. This happens on a per-repo basis (obviously, given where hub stores its tempfile).

This is a feature designed to preserve the previous pull request message if opening the PR failed (due to network error, server-side validation issues, etc.). Do you find that the PR message gets preserved and re-used in the next `hub pull-request` command even if opening the previous PR was a success?

**Comment by untitaker** [comment] 2015-04-13 14:32
> Do you find that the PR message gets preserved and re-used in the next hub pull-request command even if opening the previous PR was a success?

Yes, *sometimes*. I can't reliably reproduce this.

Would it make sense to implement this cache on a per-branch basis, i.e. include the branches' name in the tempfile-name? It's sensible behavior to preserve the message only by branch-name, and as a sideeffect it mostly fixes the problem I encounter.

I'll try to take a look at why this happens, but I can't really promise anything.

**Comment by mislav** [comment] 2015-04-13 14:34
Scoping the draft PR message per-branch sounds like a good idea.

**Comment by mislav** [comment] 2015-09-27 21:07
@danielnolan Is it possible that you haven't pushed the "dan-modify-zshrc" branch before trying to create the pull request? That could explain what we were seeing. Sorry for the late reply.

**Comment by mislav** [comment] 2016-09-14 00:01
@danielnolan I'm going to attribute your original problem to the general array of problems hub has right now with detecting of correct head & base for the new pull request. Sometimes it gets confused and doesn't pull up the correct git log information, including the commit message.

This problem is not yet fix, but I'm going to work on this soon. I'm going to close this as a duplicate of https://github.com/github/hub/issues/877 which has the same cause. Please follow that for updates. Thanks!

**Closed by mislav** 2016-09-14 00:01 UTC
Labels: unconfirmed
