### ISSUE TITLE
GitHub Enterprise issues w/ 2.x

### ISSUE THREAD

**Issue by structAnkit** [github/hub#827] opened 2015-03-02 16:56 UTC
Hub was working perfectly for me in 1.x before I updated to the new 2.2.x release last week via Homebrew. The exact error upon attempting to do a `hub pull-request` is:

`Aborted: the origin remote doesn't point to a GitHub repository.`

I haven't changed my ~/.gitconfig and everything is configured exactly as it was with the Ruby version of Hub. I believe there's some sort of if condition that is returning a failure too early when attempting to target a GitHub enterprise instance.

Is anyone else affected by this issue?

**Comment by structAnkit** [comment] 2015-03-02 21:01
Seems the remotes detected by the application only look at the push remotes. In an enterprise situation we tend to set `no_push` for this value so that we don't accidentally mess up the main repo, i.e. force pushing master.

The 1.12 version of Hub didn't have this issue as it obtained the fetch URL as well for a remote. Seems to be a regression.

**Comment by jasisk** [comment] 2015-04-01 20:15
I have an [open PR](https://github.com/github/hub/pull/830) that fixes this issue.

**Comment by mislav** [comment] 2015-04-02 08:02
> Seems the remotes detected by the application only look at the push remotes. In an enterprise situation we tend to set no_push for this value so that we don't accidentally mess up the main repo, i.e. force pushing master.

I see. Where exactly do you set `no_push`? What is the output of `git remote -v`? You can anonymize the domain/repo names as needed.

@jasisk: If the above is correct, then I don't think your PR addresses the same problem.

**Comment by jasisk** [comment] 2015-04-02 13:35
Yup. I commented without reading the rest of the thread. My mistake.

**Comment by petey** [comment] 2015-04-03 20:34
I have multiple ghe instances to use hub with and since 2.x I can only configure hub to use one at a time.

**Comment by mislav** [comment] 2015-04-03 23:17
@petey That sounds like a new problem. What happens if you try to configure more than one Enterprise instance?

**Comment by petey** [comment] 2015-04-04 04:44
I get the error displayed as shown in the original description for all but the last host in the config.

**Comment by gcochard** [comment] 2015-04-07 17:43
I have the same issue as OP, but I don't have `no_push` set on any remotes.

**Comment by mislav** [comment] 2015-09-27 22:13
I think the original issue might have been caused by the `no_push` remote. I'll close this as a duplicate of https://github.com/github/hub/issues/876#issuecomment-107748623 where there are multiple people reporting this bug. We need to support "no push" remotes in hub. We'll try to work on it.

**Closed by mislav** 2015-09-27 22:13 UTC
