### ISSUE TITLE
Feature Request: List merged pull requests

### ISSUE THREAD

**Issue by itaranto** [github/hub#1967] opened 2018-12-14 15:30 UTC
Right now is not possible to list only the merged pull requests, the only two possible states for PRs are either open or closed.

I'm not familiar with Github's REST API, is it possible to know if a PR was merged using this API?

Thanks.

**Comment by mislav** [comment] 2018-12-17 14:20
`--state=merged` isn't possible as an API query; see https://github.com/github/hub/issues/1815#issuecomment-406532323 for more discussion. But, I have some ideas how we can emulate it: we can query by `state=closed` and show only PRs that have a `merged_at` date.

Closing as duplicate of the aforementioned ticket; follow that for updates!

**Closed by mislav** 2018-12-17 14:20 UTC
