### ISSUE TITLE
How to pass social preview image to the repository during $ hub create?

### ISSUE THREAD

**Issue by marvindanig** [github/hub#2175] opened 2019-06-21 15:32 UTC
Hey!,

I'm using node shell script to create repositories automatically on Github like so:

```node
	let commitMessage = `Commit by 💎abbey@bot on ${month}, ${year}`
	let repoDescription = `Superbook ${currentBook.title} by ${currentBook.author}`

	shell.exec(`git init`)
	shell.exec(`git add . -A`)
	shell.exec(`git commit -m "${commitMessage}"`)
	shell.exec(`hub create -d "${repoDescription}" -h "${bookUrlOnBubblin}"`)
	shell.exec(`git push -u origin master`)
```

I want to pass a _social preview image_ into the repository and check the _template_repository_ option. Is there a way to do it using hub?

**Comment by mislav** [comment] 2019-06-21 17:17
Hi, good question, but none of these features are available over GitHub API.

Repository templates might be available in the near future over the API (follow https://github.com/github/hub/issues/2163) for updates, but repository images is less likely. The problem is uploading images is too much complexity to build on the command-line and I fear that wouldn't see much use even if it was built. For now and likely the long run, you will have to upload repository images manually.

If the GitHub API changes, we'll be sure to add these features as a parameters to `hub create`. But for now, I'll close this to keep the size of issue backlog down.

**Closed by mislav** 2019-06-21 17:17 UTC

**Comment by marvindanig** [comment] 2019-06-21 18:26
🤟
