### ISSUE TITLE
hub pull-request default base branch should be the same as in the web interface

### ISSUE THREAD

**Issue by wlads** [github/hub#850] opened 2015-03-21 16:19 UTC
after creating a ``pull-request``without explicitly give the branch name it creates using base **master** and my default branch to create PR using the web interface uses base **develop**. shouldn't it use the same default branch option?

**Comment by mislav** [comment] 2015-03-23 23:44
Please see https://github.com/github/hub/issues/814#issuecomment-75489117

**Comment by mislav** [comment] 2015-09-27 17:16
Closing as duplicate of the above issue

**Closed by mislav** 2015-09-27 17:16 UTC
