### ISSUE TITLE
hub create fails in existing repository

### ISSUE THREAD

**Issue by soniah** [github/hub#890] opened 2015-05-08 10:57 UTC
If I have an existing repository with a remote already setup, ```hub create``` creates the repository on githut, but issues a failure message and doesn't update **origin**. For example

```
% git remote -v
bourke  sonia@bourke.snowfrog.net:git/snowfrog/haskell-prj-apr.git (fetch)
bourke  sonia@bourke.snowfrog.net:git/snowfrog/haskell-prj-apr.git (push)
origin

% hub create
fatal: remote origin already exists.

% git remote -v
bourke  sonia@bourke.snowfrog.net:git/snowfrog/haskell-prj-apr.git (fetch)
bourke  sonia@bourke.snowfrog.net:git/snowfrog/haskell-prj-apr.git (push)
origin
```
A more sensible default would be to prompt to overwrite the existing **origin** remote, or if it is empty just overwrite it. Part of the issue here is that recently ```git init``` seems to have changed to add an empty **origin** remote by default, which is kind of annoying.

**Comment by jingweno** [comment] 2015-05-08 14:17
What's your `hub` version by running `hub version`? It should only [print `remote origin already exists`](https://github.com/github/hub/blob/master/commands/create.go#L95) instead of a fatal stop of the program.

> Part of the issue here is that recently git init seems to have changed to add an empty origin remote by default, which is kind of annoying.

This sounds strange. What's you git version?

**Comment by soniah** [comment] 2015-05-08 22:57
% hub --version
git version 2.3.3
hub version 2.2.1

**Comment by mislav** [comment] 2015-09-27 19:00
Hi @soniah, sorry that you had having trouble. This is caused by the empty "origin" remote. I just tried with git 2.3 and it doesn't seem that `git init` is supposed to create an empty "origin" remote. Could it be that something on your system added it, like a buggy setup script?

Anyway, `hub create` wasn't really designed to be used within the context of an existing repository that already has other remotes. If there is an existing repository on GitHub that you cloned locally, it's more likely that you want to `hub fork` it.

Can you check on your system does creating a new directory and calling `git init` really add an empty "origin" remote?

**Comment by mislav** [comment] 2016-01-22 10:45
Closing due to this being a configuration error. Please comment is this is still causing trouble!

**Closed by mislav** 2016-01-22 10:45 UTC
Labels: unconfirmed

**Comment by soniah** [comment] 2016-01-22 11:56
Yes, leave it closed. *User error* - in my `~/.gitconfig` I had an entry to automatically add github pull requests to the `origin` remote. Hub was therefore getting itself into a mess.

**Comment by mislav** [comment] 2016-01-22 12:43
Thanks for the update!
