### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by yfr** [github/hub#1156] opened 2016-04-06 10:10 UTC
Are there plans to support pull request templates and issue templates? Would be nice when my editor opened with the PR Templates from the comandline. The templates a in the local copy of the repo anyway. Sould be easy.

Or do i missing some option?

**Comment by yfr** [comment] 2016-04-06 10:17
Ah just after writing the Issue I found the option `-F` for the `pull-request` and I can use the `PULL_REQUEST_TEMPLATE.md`. But I can not edit this message. It's directly added to the PR and posted to Github.

Is there a possibility to use the `PULL_REQUEST_TEMPLATE.md` but edit it before submitting the PR?

**Comment by hkdobrev** [comment] 2016-04-06 10:38
Duplicate of #1118 which is being addressed by #1145.

**Comment by mislav** [comment] 2016-04-06 11:17
Yes, duplicate. Thanks for the suggestion though!

**Closed by mislav** 2016-04-06 11:17 UTC

**Comment by yfr** [comment] 2016-04-06 11:21
Ah sorry search for pull request template before opening the issue.

Just missed it.
