### ISSUE TITLE
hub rejects private github certificate

### ISSUE THREAD

**Issue by benson-basis** [github/hub#1040] opened 2015-12-01 21:32 UTC
What do I do about the following? (A result of upgrading my copy of 'hub').

Post https://git.basistech.net/api/v3/repos/raas/rosapi1.5/pulls: x509: certificate signed by unknown authority

**Comment by mislav** [comment] 2015-12-02 08:16
I'm sorry, but we already know about this, but don't know how to solve it: https://github.com/github/hub/issues/852#issuecomment-85704103

The reality is, we don't know where Go looks for custom certificates. I thought that on OS X, for example, adding a certificate to KeyChain would be enough, but it might be more involved than that.

We might need to add a configuration option that allows one to specify a custom certificate when speaking to an Enterprise host.

I'm going to close this as a duplicate of the referenced issue. So sorry that you're having trouble.

**Closed by mislav** 2015-12-02 08:16 UTC
