### ISSUE TITLE
`git pull-request` not reading head project correctly

### ISSUE THREAD

**Issue by SpainTrain** [github/hub#944] opened 2015-07-06 21:47 UTC
When attempting to `git pull-request`, `hub` does not appear to be using the correct local branch info.  I believe everything is configured as described in `git pull-request -h`:

> Opens a pull request on GitHub for the project that the "origin" remote points to. The default head of the pull request is the current branch.

The relevant configs and command outputs are:

```bash
$ git remote -v
SpainTrain	git@github.com:SpainTrain/express-jsonschema.git (fetch)
SpainTrain	git@github.com:SpainTrain/express-jsonschema.git (push)
origin	git://github.com/trainiac/express-jsonschema.git (fetch)
origin	git@github.com:trainiac/express-jsonschema.git (push)

$ git status
On branch allow-split-schema
Your branch is up-to-date with 'SpainTrain/allow-split-schema'.
nothing to commit, working directory clean

$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git://github.com/trainiac/express-jsonschema.git
	fetch = +refs/heads/*:refs/remotes/trainiac/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "SpainTrain"]
	url = git@github.com:SpainTrain/express-jsonschema.git
	fetch = +refs/heads/*:refs/remotes/SpainTrain/*
[branch "allow-split-schema"]
	remote = SpainTrain
	merge = refs/heads/allow-split-schema

$ git --noop pull-request -m "Allow Split Schemas"
Would request a pull request to trainiac:master from trainiac:allow-split-schema 
echo PULL_REQUEST_URL
```

Given that the current branch is tracking `SpainTrain:allow-split-schema` and `origin` is `trainiac/express-jsonschema`, it seems like that should read `pull request to trainiac:master from SpainTrain:allow-split-schema`.  Am I missing something?

Also, I cloned the repo using the `trainiac/express-jsonschema` syntax and used `hub fork` to create the SpainTrain remote.

**Comment by SpainTrain** [comment] 2015-07-09 03:59
```bash
$ git --version
git version 2.1.0
hub version 2.2.1

```

**Comment by mislav** [comment] 2015-09-27 18:12
@SpainTrain You're right with your assumption, and sorry for the late reply.

Did the "origin" remote also have a branch called "allow-split-schema" pushed to it? That might have confused the `pull-request` command.

Does your issue still persist?

**Comment by mislav** [comment] 2015-09-27 18:27
I'm gonna close this as a duplicate of a very similar report: #928

Thanks for reporting!

**Closed by mislav** 2015-09-27 18:27 UTC
Labels: pull-request, unconfirmed
