### ISSUE TITLE
Hub tries to create PR against upstream remote automatically. Origin & Upstream owned by same owner.

### ISSUE THREAD

**Issue by generalredneck** [github/hub#1997] opened 2019-01-03 16:35 UTC
So I've been reading and found that hub does some magic using the "upstream" remote as the default remote for doing a PR. In all the cases where someone has asked about this, they are told to use the verbose OWNER:branch syntax... In this case, my organization owns both the upstream AND the origin repositories. The usecase is like this... We have a custom "Pantheon Upstream" for our drupal sites. We also build our drupal sites. I'm trying to automate the pull of the pantheon upstream into all the sites. It so happens I use the name "upstream" and was expecting this to go to origin or at least the remote the branch was tracking against...

Is there any way to specify the remote specifically or at least the repository?

This is different than #1618 and the comment in https://github.com/github/hub/issues/381#issuecomment-23617252 is flat out wrong when you have this usecase.

**Comment by generalredneck** [comment] 2019-01-03 16:44
FYI, the work around here is rename my remotes from upstream to drupal_upstream and it goes about it's business using origin. Since this is scripted... this isn't a big deal but usability and workflow that has been establish has to change for the tool to work.

**Comment by mislav** [comment] 2019-01-03 19:54
Do you have at least hub version 2.7.0? If "upstream" is pointing to a repository that's _not_ on GitHub, then it will be ignored. If Drupal upstream is indeed a URL to GitHub, then it's true: the only way for you to choose a different remote, unfortunately, is the `-b OWNER:branch` syntax (or rename the "upstream" remote, which I don't recommend because it breaks your existing conventions).

I hope that some sort of configuration option exists for this in the next release, but I haven't yet been inspired on how to properly implement this.

**Comment by generalredneck** [comment] 2019-01-04 02:31
Yes both repos are on github under the same owner "fourkitchens" in this case. I'll make it work and only have the remote name change for scripted instances and just make sure it's a documented process that of they use hub for cli PRs that this is the current case.

For clarity a facsimile of my situation is as follows
Upstream is git@github.com:fourkitchens/upstream.git
Origin is git@github.com:fourkitchens/origin.git

**Comment by mislav** [comment] 2019-01-18 03:39
Thank you for detailing your use case! I will close this since you have 2 workarounds available to you and since the preference of "upstream" (although unwanted in your case) is by design. Future releases of hub might have a configuration system where you can choose your preferred remote name to base PRs off.

**Closed by mislav** 2019-01-18 03:39 UTC

**Comment by bendulum** [comment] 2019-07-23 10:07
Any chance this is getting picked up again? I'm running into the exact same issue, but simply renaming `upstream` isn't a desirable workaround for me. Maybe this could be solved by a simple flag eg. `hub pull-request --force-remote "origin"` as an intermediary solution?
Thanks.
