### ISSUE TITLE
no bash completion for pull-request

### ISSUE THREAD

**Issue by yurikoles** [github/hub#1875] opened 2018-09-16 19:28 UTC
Bash completion doesn't know pull-request command.

**Comment by mislav** [comment] 2018-09-17 11:38
Thanks for reporting. What is your OS and git version?

**Comment by yurikoles** [comment] 2018-09-17 11:48
Git 2.19.0/macOS 10.14b11 (Mojave).
Same issue with Git and hub from master. 
I have no aliases for hub.

**Comment by mislav** [comment] 2018-09-17 14:17
Because of how git core bash completions are implemented, in order for hub to extend them, git has to be aliased as hub for now. I haven't been able to work around this, so contributions/fixes welcome.

Try this:

1. Open a new shell;
2. `alias git=hub`;
3. type `git pu` and press <kbd>Tab</kbd> twice.

Does `pull-request` show?

**Comment by yurikoles** [comment] 2018-09-17 18:13
yes, it shown

**Comment by mislav** [comment] 2018-09-18 08:26
Thank you for checking. Then I'll close this as a duplicate of #1792.

In order to get hub aliases working for now, add `alias git=hub` to your `~/.bash_profile`. The completions should also work if your start the command with `hub`:

```
$ hub pull-request <TAB>
```

**Closed by mislav** 2018-09-18 08:26 UTC
Labels: unconfirmed
