### ISSUE TITLE
Not reporting multiple ci-status'

### ISSUE THREAD

**Issue by kholbekj** [github/hub#995] opened 2015-09-15 09:10 UTC
![delete_a_job_for_mechanic_when_cancelling_his_offer_by_kholbekj_ _pull_request__3858_ _autobutler_autobutler](https://cloud.githubusercontent.com/assets/2786571/9872543/3fa1ee44-5b9a-11e5-9b10-fded57c30951.png)
```
 ⚓  ~/s/a/  khj/make-mechanic-deletion-on-cancel  git ci-status
success
```

**Comment by mislav** [comment] 2015-09-26 17:51
Thanks for reporting! This is a duplicate of #943.

**Closed by mislav** 2015-09-26 17:51 UTC
