### ISSUE TITLE
Cannot use hub pr checkout after PR was updated

### ISSUE THREAD

**Issue by nh2** [github/hub#2448] opened 2020-01-20 19:43 UTC
**Command attempted:**

```
$ hub pr checkout 1234

# now somebody force-pushes the PR to incorporate feedback

$ hub pr checkout 1234
fatal: Refusing to fetch into current branch refs/heads/mybranch of non-bare repository
```

**What happened:**

`hub` fails with an internal git error.

As a user I want to get the new changes from the PR with the incorporated feedback.

`hub` should either do that, or tell me why I somehow can't get that (and perhaps actionable infon on what I should do instead), instead of failing with an internal git error message.

**More info:**

```
git version 2.23.1
hub version 2.12.7
```

on NixOS Linux 19.09.

**Comment by nh2** [comment] 2020-01-20 20:25
A workaround seems to be to `git checkout` another branch, then `git branch -D mybranch` to delete the branch `hub` had created, and using `hub pr checkout 1234` again so that it recreates it.

**Comment by mislav** [comment] 2020-02-20 01:55
Duplicate of https://github.com/github/hub/issues/2061

**Closed by mislav** 2020-02-20 01:55 UTC
Labels: bug
