### ISSUE TITLE
Last pull-request title is uploaded instead of new one.

### ISSUE THREAD

**Issue by bgvo** [github/hub#1146] opened 2016-03-14 14:53 UTC
When I do `git pull-request` being on a feature-branch, it opens my editor and it shows the last title and description I entered. However, once I overwrite it with the new title and description still uploads to Github the previous title and description. 

Why do we have this behavior?

Thanks.

**Comment by mislav** [comment] 2016-05-03 11:00
Hmm, that shouldn't happen. Did you remember to save the file after editing? If you exited the editor but didn't save the changes, hub would use the original title and description that were presented to you when the text editor opened, but not with any of your changes. That's the only explanation I could see.

Does this keep happening to you? If so, are you using the latest hub version?

**Comment by valentin-hc** [comment] 2016-05-03 18:34
I have the same issue. I work with @bgvo and it has been happening every time for me. 
The process usually is : save changed files, git add . , git commit, git push, git pull-request (I have git alias so it uses hub). 
It opens my editor with the description of my last pull request. I overwrite it and then save but it catches the previous text, not the one I just entered before saving.

To avoid having that problem, what I have been doing is leaving the page blank before saving on my second attempt. That way next time I do a pull request, I fill in my comment, save, it fails to execute pull request due to empty title, then I do git pull-request again, this time I erase the comment I just entered before and save the blank page. That second time it does catch the comment I had written on the first attempt.

I hope that works, let me know if you need more clarification.

**Comment by danielnolan** [comment] 2016-08-17 15:19
I am having this same issue after updating hub recently. I am currently on the most current version of hub 2.2.5 and git 2.9.3. My remote is named origin. No matter what I do now it uses the previous pull request title and body, even if I erase all of the text for the pull request when vim opens to edit the pull request message. My workflow is pretty typical

1. cut a feature branch from master
2. add changed files using `git add .` and commit using `git commit`
3. push to remote using `git push -u`
4. open pull request using `git pull-request`

**Comment by mislav** [comment] 2016-08-17 15:54
@danielnolan I'm sorry that you're having trouble. Is the problem that you're having one where you edited title & pull request body in your text editor, but those edits were ignored? Did you properly save the file when editing pull request message before closing vim? Are you using a graphical vim such as gvim or macvim?

**Comment by danielnolan** [comment] 2016-08-17 17:48
Yes when I open a pull request using hub it has the title and body from the previous pull request when vim opens. It used to have the last commit message title and body from the current branch. If I change the title and body or even delete it and submit it blank it still uses the title and body from the previous pull request. I am currently using neovim installed via homebrew, I also use tmux if that could have any effect on the issue. Hub has been part of my workflow everyday and this was all working great until version 2.2.4 I believe.

**Comment by mislav** [comment] 2016-08-17 21:48
That's pretty strange that it broke now. What's your `git var GIT_EDITOR`? If you `rm .git/PULLREQ_EDITMSG`, does the problem go away permanently?

**Comment by danielnolan** [comment] 2016-08-18 14:17
`GIT_EDITOR` is vim and I don't seem to have a `.git/PULLREQ_EDITMSG`

**Comment by mislav** [comment] 2016-08-19 13:14
@danielnolan That's how it should be, but then I don't have any explanation for the problems you are experiencing. I'm sorry. I'll keep an eye out for similar reports and will try to reproduce the issue myself. Please keep me updated on any variations of this bug.

**Comment by timja-kainos** [comment] 2017-09-14 10:01
I'm also having this issue.
I cleared my message and it still created the pull request with the old title.
```
$ git var GIT_EDITOR
nvim
```

I also don't have this file `PULLREQ_EDITMSG`

**Comment by mislav** [comment] 2019-09-29 09:19
Closing due to lack of newer reports. Sorry that this hasn't reached a satisfying conclusion! I hope it was somehow fixed in the meantime.

**Closed by mislav** 2019-09-29 09:19 UTC
Labels: more-info-needed
