### ISSUE TITLE
Documentation and/or command to update credentials

### ISSUE THREAD

**Issue by jroper** [github/hub#2791] opened 2021-06-28 23:49 UTC
I got an email from GitHub today asking me to regenerate the access token that hub uses to the new format, which I did. So I now have the new token... what do I do with it? I run `hub help`, nothing in there about authentication, tokens, configuration files, etc. I visit https://hub.github.com/, nothing there about tokens, authentication, configuration files. I go to https://github.com/github/hub, nothing there either. I try running a hub command, it just tells me `Bad credentials`, no instructions of how to update my credentials or anything. So what do I do with the token I just generated? I eventually searched issues for configuration file, and found that the configuration file for hub is `~/.config/hub`, I opened that, pasted in my token, and I'm good to go. But I shouldn't have to search unrelated issues to get the answer to something is basic as this, there should at least be documentation on how to update the token, and maybe even a command to let you set a new token for when you get emails from GitHub asking you to regenerate tokens.

**Comment by ashleyryan** [comment] 2021-06-29 15:23
I have a similar error. I get a cryptic `exit status 128` error, and then got the email to regenerate my token, which I did, but now I can't figure out how to update it. I don't have a `~/.config/hub` file in $HOME like hub docs reference and can't figure out how to update the token.

**Comment by Birdi7** [comment] 2021-06-30 11:57
I totally agree with this issue. Also, if you've deleted the `~/.config/hub` file, then there is no way to configure `hub` with any credentials. The `pull-request` command asks for username & password, and then prints `404 Not Found`, as I have 2FA enabled

**Comment by jroper** [comment] 2021-06-30 12:59
I believe when it asks you for your password, you're supposed to enter your token. [There's a PR](https://github.com/github/hub/pull/2742) to update the prompt to ask for a token rather than a password, but I'm starting to learn this repo seems dead.

**Comment by foursixnine** [comment] 2021-10-20 12:11
@jroper https://mislav.net/2020/01/github-cli/ looks like so...

**Comment by NikkiDelRosso** [comment] 2021-12-17 01:43
I don't seem to be able to set my credentials at all from the command line (hitting enter just displays `^M` using zsh in my Mac terminal rather than entering my username). Haven't been able to find documentation related to it at all yet!

**Comment by mislav** [comment] 2022-01-03 12:19
Sorry for the inconvenience, everyone. We absolutely need better behavior and better documentation around authenticating.  For the time being, I'm going to close this as a duplicate of https://github.com/github/hub/issues/2655#issuecomment-790263257

**Closed by mislav** 2022-01-03 12:19 UTC
Labels: feature
