### ISSUE TITLE
hub create ignores organization

### ISSUE THREAD

**Issue by derrickburns** [github/hub#2261] opened 2019-09-09 21:02 UTC
```
$hub create tidepool-org/cluster-test3
Updating origin
https://github.com/derrickburns/cluster-test3
$hub version
git version 2.22.0
hub version 2.12.4
```

**Comment by mislav** [comment] 2019-09-10 16:15
Thank you for reporting. This is really puzzling. We have a test that verifies that this format of invocation should work https://github.com/github/hub/blob/4aba5854179b8e381bebd08ec9b2d49a3613eb15/features/create.feature#L63-L65

Could you try again with `HUB_VERBOSE=1 hub create ...` and report if anything stands out to you?

**Comment by derrickburns** [comment] 2019-09-10 18:37
```
$  HUB_VERBOSE=1 hub create tidepool-org/barbar
$ git rev-parse -q --git-dir
> GET https://api.github.com/repos/tidepool-org/barbar
> Authorization: token [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
< HTTP 404
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"}
> POST https://api.github.com/user/repos
> Authorization: token [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
{"description":"","homepage":"","name":"barbar","private":false}
< HTTP 201
< Location: https://api.github.com/repos/derrickburns/barbar
{"id":207635459,"node_id":"MDEwOlJlcG9zaXRvcnkyMDc2MzU0NTk=","name":"barbar","full_name":"derrickburns/barbar","private":false,"owner":{"login":"derrickburns","id":583930,"node_id":"MDQ6VXNlcjU4MzkzMA==","avatar_url":"https://avatars1.githubusercontent.com/u/583930?v=4","gravatar_id":"","url":"https://api.github.com/users/derrickburns","html_url":"https://github.com/derrickburns","followers_url":"https://api.github.com/users/derrickburns/followers","following_url":"https://api.github.com/users/derrickburns/following{/other_user}","gists_url":"https://api.github.com/users/derrickburns/gists{/gist_id}","starred_url":"https://api.github.com/users/derrickburns/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/derrickburns/subscriptions","organizations_url":"https://api.github.com/users/derrickburns/orgs","repos_url":"https://api.github.com/users/derrickburns/repos","events_url":"https://api.github.com/users/derrickburns/events{/privacy}","received_events_url":"https://api.github.com/users/derrickburns/received_events","type":"User","site_admin":false},"html_url":"https://github.com/derrickburns/barbar","description":null,"fork":false,"url":"https://api.github.com/repos/derrickburns/barbar","forks_url":"https://api.github.com/repos/derrickburns/barbar/forks","keys_url":"https://api.github.com/repos/derrickburns/barbar/keys{/key_id}","collaborators_url":"https://api.github.com/repos/derrickburns/barbar/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/derrickburns/barbar/teams","hooks_url":"https://api.github.com/repos/derrickburns/barbar/hooks","issue_events_url":"https://api.github.com/repos/derrickburns/barbar/issues/events{/number}","events_url":"https://api.github.com/repos/derrickburns/barbar/events","assignees_url":"https://api.github.com/repos/derrickburns/barbar/assignees{/user}","branches_url":"https://api.github.com/repos/derrickburns/barbar/branches{/branch}","tags_url":"https://api.github.com/repos/derrickburns/barbar/tags","blobs_url":"https://api.github.com/repos/derrickburns/barbar/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/derrickburns/barbar/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/derrickburns/barbar/git/refs{/sha}","trees_url":"https://api.github.com/repos/derrickburns/barbar/git/trees{/sha}","statuses_url":"https://api.github.com/repos/derrickburns/barbar/statuses/{sha}","languages_url":"https://api.github.com/repos/derrickburns/barbar/languages","stargazers_url":"https://api.github.com/repos/derrickburns/barbar/stargazers","contributors_url":"https://api.github.com/repos/derrickburns/barbar/contributors","subscribers_url":"https://api.github.com/repos/derrickburns/barbar/subscribers","subscription_url":"https://api.github.com/repos/derrickburns/barbar/subscription","commits_url":"https://api.github.com/repos/derrickburns/barbar/commits{/sha}","git_commits_url":"https://api.github.com/repos/derrickburns/barbar/git/commits{/sha}","comments_url":"https://api.github.com/repos/derrickburns/barbar/comments{/number}","issue_comment_url":"https://api.github.com/repos/derrickburns/barbar/issues/comments{/number}","contents_url":"https://api.github.com/repos/derrickburns/barbar/contents/{+path}","compare_url":"https://api.github.com/repos/derrickburns/barbar/compare/{base}...{head}","merges_url":"https://api.github.com/repos/derrickburns/barbar/merges","archive_url":"https://api.github.com/repos/derrickburns/barbar/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/derrickburns/barbar/downloads","issues_url":"https://api.github.com/repos/derrickburns/barbar/issues{/number}","pulls_url":"https://api.github.com/repos/derrickburns/barbar/pulls{/number}","milestones_url":"https://api.github.com/repos/derrickburns/barbar/milestones{/number}","notifications_url":"https://api.github.com/repos/derrickburns/barbar/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/derrickburns/barbar/labels{/name}","releases_url":"https://api.github.com/repos/derrickburns/barbar/releases{/id}","deployments_url":"https://api.github.com/repos/derrickburns/barbar/deployments","created_at":"2019-09-10T18:36:38Z","updated_at":"2019-09-10T18:36:38Z","pushed_at":"2019-09-10T18:36:39Z","git_url":"git://github.com/derrickburns/barbar.git","ssh_url":"git@github.com:derrickburns/barbar.git","clone_url":"https://github.com/derrickburns/barbar.git","svn_url":"https://github.com/derrickburns/barbar","homepage":"","size":0,"stargazers_count":0,"watchers_count":0,"language":null,"has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":0,"license":null,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master","permissions":{"admin":true,"push":true,"pull":true},"allow_squash_merge":true,"allow_merge_commit":true,"allow_rebase_merge":true,"network_count":0,"subscribers_count":1}
$ git remote -v
$ git config --get-all hub.host
A git remote named 'origin' already exists and is set to push to 'ssh://git@github.com/derrickburns/cluster-test.git'.
https://github.com/derrickburns/barbar
```

**Comment by mislav** [comment] 2019-09-11 14:01
Thank you for the info! I still cannot reproduce this. Do you have `GITHUB_USER` (or any other "GITHUB"/"HUB"-related) variables set in your environment?

**Comment by mislav** [comment] 2019-09-30 14:33
@derrickburns Is still still an issue? So far, I don't have enough information to reproduce this bug. More details about your environment would help me out.

**Comment by derrickburns** [comment] 2019-09-30 15:24
I understand.  I have been rather busy. I can try to reproduce again later this week.

Derrick Burns

**Comment by mislav** [comment] 2019-10-01 10:42
@derrickburns Take your time. I will leave this open for now. 🙇

**Comment by mislav** [comment] 2020-01-14 16:19
@derrickburns Friendly ping. If this is no longer an active issue for you, please close it. Thank you!

**Comment by NSExceptional** [comment] 2020-04-28 02:01
This may be an unrelated issue but I'm not sure. I created a repo locally, committed, etc, then ran `hub create my-org/my-repo`. I was prompted for login, and the repo was created (despite it saying no repo was created):

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
Tanners-MBP:FixPhotos tanner$ hub create NSCake/NoScreenshots
Existing repository detected
https://github.com/NSCake/NoScreenshots
```

But no `master` branch was created on the remote repo.

**Comment by mislav** [comment] 2020-05-11 14:04
@NSExceptional I think hub tried to add an `origin` remote using the SSH-style (`git@github.com:...`) of URLs, but you don't seem to have SSH key authentication set up, so you maybe prefer HTTPS git URLs instead? Then please do `git config --global hub.protocol https`, remove the origin remote (`git remote rm origin`) and try `hub create` again

**Comment by NSExceptional** [comment] 2020-06-03 19:56
@mislav Thanks! That did the trick.

**Comment by Alexis1956** [comment] 2021-07-02 05:31
Try I didn't do anything you all just want to set me up to take my money

**Comment by mislav** [comment] 2021-09-04 10:13
Closing due to lack of reproducible info.

**Closed by mislav** 2021-09-04 10:13 UTC
Labels: more-info-needed
