### ISSUE TITLE
hub.bash_completion.sh syntax error breaking Xsession

### ISSUE THREAD

**Issue by genebean** [github/hub#1039] opened 2015-11-28 22:48 UTC
After installing the hub.bash_completion.sh to `/etc/profile.d/` and rebooting I get the following error in my `.xsession-errors` file:

``` bash
/etc/mdm/Xsession: Beginning session setup...
/etc/mdm/Xsession: 203: /etc/profile.d/hub.bash_completion.sh: Syntax error: "(" unexpected (expecting ";;")
```

I am on Linux Mint 17.2 and mdm fails to start. Once started manually, it comes up and I can log in but it logs me out immediately with the error above. I am using the pre-built v2.2.2 release of Hub.

**Comment by mislav** [comment] 2015-11-30 12:42
Thanks for reporting. What is your version of bash?

**Comment by genebean** [comment] 2015-12-03 23:30
Looks like 4.3-7ubuntu1.5 per http://packages.ubuntu.com/trusty-updates/shells/bash. That computer is at the office so I can't check in person at the moment but this should be accurate.

**Comment by phansys** [comment] 2016-01-13 03:22
Hi @mislav.
I can confirm this issue:
```bash
$ bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
```

**Comment by mislav** [comment] 2019-02-07 01:00
Sorry I didn't get around to investigating this. This was a long time ago, and since then we didn't have similar reports, so I'm going to close this until someone has more information on how to proceed/what to fix.

**Closed by mislav** 2019-02-07 01:00 UTC
Labels: unconfirmed
