### ISSUE TITLE
Error creating repository: Not Found (HTTP 404)

### ISSUE THREAD

**Issue by belaldata** [github/hub#2703] opened 2021-01-31 08:38 UTC
**Command attempted:**

HUB_VERBOSE=1 hub create

**What happened:**

$ git rev-parse -q --git-dir
$ git rev-parse --show-toplevel
github.com username: belaldata
github.com password for belaldata (never stored): 
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
{"note":"hub for belalnoor@Belals-Air","note_url":"https://hub.github.com/","scopes":["repo","gist"]}
< HTTP 404
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Error creating repository: Not Found (HTTP 404)
Not Found

**More info:**

git version 2.30.0
hub version refs/heads/master

macOS Big Sur version 11.1,
Chip Apple M1

Steps to produce the error,
1. brew install hub
2. git init
3 git add .
4 git commit -m "And so, it begins."
5 hub create/HUB_VERBOSE=1 hub create

**Comment by josfk** [comment] 2021-02-15 12:17
Same problem here, also in BigSur

**Comment by cmcaine** [comment] 2021-02-15 15:49
This is a known issue, workaround here: https://github.com/github/hub/issues/2655#issuecomment-735836048

**Comment by mislav** [comment] 2021-02-19 09:13
Closing as duplicate of the referenced issue

**Closed by mislav** 2021-02-19 09:13 UTC
Labels: bug
