### ISSUE TITLE
hub-pr should support searching through PRs

### ISSUE THREAD

**Issue by colemickens** [github/hub#2588] opened 2020-08-07 04:52 UTC
**The problem I'm trying to solve:**
I am not sure if I'm missing something. Is there no way to search PRs with this tool?

Hub is prohibitively slow when used against a repo like nixos/nixpkgs.

**How I imagine hub could expose this functionality:**
`hub pr search <search term> --status=open`

or `hub pr list --search "term"`

**Comment by mislav** [comment] 2020-08-12 11:22
Duplicate of https://github.com/github/hub/issues/833

In the meantime, you can use this to search for PRs mentioning "alpine", for example:
```sh
hub api -XGET search/issues -f q="is:pr repo:nixos/nixpkgs alpine" | jq -r '.items[] | ([.number,.state,.title] | @tsv)'
```

**Closed** 2020-08-12 11:22 UTC
Labels: feature
