### ISSUE TITLE
Reviewing pull requests with git difftool

### ISSUE THREAD

**Issue by woolie** [github/hub#631] opened 2014-10-08 22:54 UTC
I would love to be able to list outstanding pull requests, pick one to review using git difftool (which in my case fires up a gui diff tool).

**Comment by brandonweiss** [comment] 2015-04-10 17:17
Listing pull requests (specifically open ones) would be awesome. I know I can add the pulls namespace to origin fetch, but the problem is that has _all_ pull requests, not just open ones. On a small repo that's fine, but I work on a repo with 17k+ pull requests. I had to stop doing that because it made autocomplete take 10+ seconds.

**Comment by mislav** [comment] 2019-01-26 19:46
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

Thank you for suggesting!

**Closed by mislav** 2019-01-26 19:46 UTC
Labels: feature

**Comment by geoffreywiseman** [comment] 2019-02-05 16:03
If someone *does* implement a script, link to it here. ;) I'm not ready to do it myself, but I totally want this feature.

**Comment by VladimirUAZ** [comment] 2019-09-17 15:54
Here's a windows bat script that I made for myself [PrDifftool.bat](https://github.com/VladimirUAZ/CommandLineUtils/blob/master/PrDifftool.bat) @geoffreywiseman
