### ISSUE TITLE
hub pull-request for existing pull request

### ISSUE THREAD

**Issue by sfahlberg** [github/hub#1451] opened 2017-04-12 20:54 UTC
I'm wondering if there's a way for me to open up an existing pull request using hub. I can go to the branch page using `hub browse` or `hub compare` but I want to be able to see my existing PR when  I run `hub pull-request`and it detects a pr, it would open that page up in a browser for the developer to inspect

**Comment by mislav** [comment] 2017-06-26 09:44
Agreed! This is a duplicate of #897.

**Closed** 2017-06-26 09:44 UTC
