### ISSUE TITLE
Feature request: Fork before cloning

### ISSUE THREAD

**Issue by tuzmusic** [github/hub#2000] opened 2019-01-07 08:06 UTC
Add ability to pass `fork` command a repo url, rather than needing to fork a project that’s already been cloned to your machine.

**Comment by mislav** [comment] 2019-01-07 11:07
Thank you for the suggestion! This has been requested a few times before, so I'm going to close this as duplicate of https://github.com/github/hub/issues/348

**Closed by mislav** 2019-01-07 11:07 UTC
