### ISSUE TITLE
hub doesn't recognize `shortlog -sne`

### ISSUE THREAD

**Issue by fperez** [github/hub#1639] opened 2017-12-30 06:28 UTC
Since it's recommended to alias `git` to `hub`, I assume that it should pass-through all unrecognized options unmodified to the underlying `git`. If that's correct, then I think this qualifies as a bug:

```
(master)alpamayo[ipykernel]> hub shortlog -sne
fatal: unrecognized argument: -sne
(master)alpamayo[ipykernel]> /usr/local/bin/git shortlog -sne
   804  Foo Bar <foo@bar.com>
...
```

Thanks for the great tool!

**Comment by ritiek** [comment] 2018-01-19 11:21
I can't reproduce this via git master:
```
$ hub shortlog -sne
804  Foo Bar <foo@bar.com>
...
```
```
$ hub --version
git version 2.14.1
hub version 2.3.0-pre10-51-g55dec7d
```

**Comment by mislav** [comment] 2018-01-19 16:01
Yes I think this was fixed in master in the meantime. Thanks for reporting, and please try out the prereleases in the Releases section!

**Closed by mislav** 2018-01-19 16:01 UTC
