### ISSUE TITLE
Switch accounts by repositories

### ISSUE THREAD

**Issue by ryamaguchi0220** [github/hub#2491] opened 2020-03-04 08:46 UTC
**The problem I'm trying to solve:**

I faced a case that I would like to switch accounts by repositories, but as far as I know, it is not supported.

**How I imagine hub could expose this functionality:**

Here is a configuration example that I imagine
```
github.com:
- user: userA 
  oauth_token: brabra
  protocol: https
  repository: userA/repositoryA // when operations to this repository are performed, use the userA account
- user: userB // when operations to other repositories are performed, use the userB account
  oauth_token: brabra
  protocol: https
```

**Comment by mislav** [comment] 2020-03-04 11:54
Thanks for writing in! This is planned but no work has been done yet. Duplicate of  https://github.com/github/hub/issues/1300

**Closed by mislav** 2020-03-04 11:54 UTC
Labels: feature
