### ISSUE TITLE
hub ask me unnecessary login information

### ISSUE THREAD

**Issue by c01o** [github/hub#1947] opened 2018-11-24 00:25 UTC
Cloning public repos should not need a github account, but `hub` force me to login github.
```console
$ git clone https://github.com/github/hub.git
Cloning into 'hub'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 16088 (delta 11), reused 18 (delta 9), pack-reused 16059
Receiving objects: 100% (16088/16088), 4.98 MiB | 462.00KiB/s, done.
Resolving deltas: 100% (10231/10231), done.
Checking connectivity... done.

$ hub clone github/hub
github.com username:
github.com password for  (never stored):
Error getting repository: Unauthorized (HTTP 401)
Bad credential
```

For private repo, `hub` ignore ssh credentials while `git` make good use of.
```console
$ git clone git@github.com:c01o/private-repo.git
Cloning into 'private-repo'...
(clone properly)

$ git config --global hub.protocol
ssh

$ hub clone c01o/private-repo
github.com username:
github.com password for  (never stored):
Error getting repository: Unauthorized (HTTP 401)
Bad credential
```

**Comment by mislav** [comment] 2018-11-26 14:54
Hi thank you for reporting. I can see how this is surprising. Most hub operations need access to GitHub API, and even though you're operating on a public repo now, sooner or later there will be an API request to a private repo and you would need to authenticate. That's why hub offers to authenticate you as a one-time operation the first time you use *any* hub feature.

Closing this as duplicate of https://github.com/github/hub/issues/1839 which has more context and discussion. Avoiding prompting for authentication for public repos is definitely something that we could do as a feature, so follow the other issue for updates.

**Closed by mislav** 2018-11-26 14:54 UTC
