### ISSUE TITLE
list pr's by label

### ISSUE THREAD

**Issue by meyn** [github/hub#2365] opened 2019-11-18 16:00 UTC
**The problem I'm trying to solve:**
Our CI periodically creates PR's with things like translations (from a 3rd party server) which we review and merge etc..
However if we don't merge a previous PR (like on a holiday for e.g.) we end up with multiple PR's that conflict each other (if anything other than the latest ones is merged first).
Allowing listing of PR's that use the same labels (CI specific labels) would help by having the hub CLI close the previous PR when it starts to create a new one.

**How I imagine hub could expose this functionality:**
`hub pr list -l <label1>,<label2>`

**Comment by mislav** [comment] 2019-11-18 22:16
Good idea! Closing as duplicate of https://github.com/github/hub/issues/2084

**Closed by mislav** 2019-11-18 22:16 UTC
Labels: feature
