### ISSUE TITLE
Git aliases only work intermittently when invoked by hub on WSL

### ISSUE THREAD

**Issue by lonnon** [github/hub#2009] opened 2019-01-18 21:09 UTC
In Ubuntu on Windows Subsystem for Linux, using `hub` to invoke git
works only part of the time. When it fails, there is no text printed by
the command, and it has a return code of 1.

```sh
# ~/.gitconfig

[alias]
  st = status
```

```sh
~/repo % hub st

~/repo % hub st

~/repo % hub st
On branch master

No commits yet

nothing to commit (create/copy files and use "git add" to track)

~/repo % echo $?
0

~/repo % hub st

~/repo % echo $?
1
```

The bug does not reproduce on a native copy of Ubuntu.

Environment:
```
Windows Version 10.0.17134 Build 17134
Ubuntu 18.04.1 LTS

git version 2.17.1
hub version 2.7.1
```

I've been able to reproduce this with several different aliased commands:

```
[alias]
  co = checkout
  ls = log --stat
   d = diff
```

**Comment by mislav** [comment] 2019-01-21 12:03
Hi thank you for reporting! Do you think this might be a duplicate of https://github.com/github/hub/issues/1871?

**Comment by lonnon** [comment] 2019-01-23 19:08
After tinkering with it a bit, I think you're right; this does look like the same symptoms as #1871.

I get similar behavior when running under `HUB_VERBOSE=1`; it produces the same output whether the command succeeds or fails:

```sh
% HUB_VERBOSE=1 hub st
$ git config alias.st
$ git help --no-verbose -a
$ git help -a
$ git status
fatal: not a git repository (or any of the parent directories): .git

% HUB_VERBOSE=1 hub st
$ git config alias.st
$ git help --no-verbose -a
$ git help -a
$ git status

%
```

Also, the Windows version of hub (installed via `scoop`) has no trouble at all with aliases. This all seems consistent with the behavior GabrielDuarteM describes. Hopefully it's something that the WSL folks over at Microsoft can address at some point.

In the meantime, I can use hub without aliasing it as git. Not as convenient, but I currently only use hub for pull requests, anyhow. Thanks for looking into this!

**Comment by mislav** [comment] 2019-01-24 01:47
Thank you for updating! I'm going to close this as a duplicate. 👍

**Closed by mislav** 2019-01-24 01:47 UTC

**Comment by minipitbull** [comment] 2019-01-26 04:51
That's fine
