### ISSUE TITLE
Git-cli login with 2fa

### ISSUE THREAD

**Issue by Aayush9029** [github/hub#2465] opened 2020-02-07 17:25 UTC
**Using a web interface to login to github-cli (2fa)**
> Login through a web interface like heroku does for their cli sessions

**How I imagine hub could expose this functionality:**
> `hub git-login` 

> *Or (save the login details) so i don't have to paste my access token every time i need to push*

**Comment by mislav** [comment] 2020-02-20 02:14
Duplicate of https://github.com/github/hub/issues/889

**Closed by mislav** 2020-02-20 02:14 UTC
Labels: feature
