### ISSUE TITLE
Can't enter auth credentials on Windows

### ISSUE THREAD

**Issue by garfieldnate** [github/hub#815] opened 2015-02-20 12:22 UTC
I'm trying to send a PR for an existing issue, but I can't finish entering my credentials before hub fails:

    >hub.exe pull-request -i 777 -b branch_name
    github.com username: garfieldnate
    github.com password for garfieldnate (never stored):
    Error creating pull request: Unauthorized (HTTP 401)
    Bad credentials
    >password

It fails while I'm entering my password and then the password gets put into the cmd afterwards, as shown.

Using Windows 7 64 bit, git version 1.9.4.msysgit.0

**Comment by mislav** [comment] 2015-02-23 04:17
Thanks for reporting. This could be a Windows bug. Can you please tell us your `hub version`?

**Comment by garfieldnate** [comment] 2015-02-23 08:39
Certainly:
git version 1.9.4.msysgit.0
hub version 2.2.0

**Comment by twsouthwick** [comment] 2015-03-08 18:34
I had issues with this as well when I tried setting it up on a new windows machine (Win10 64-bit).  I couldn't type my password in - it only allows 11 characters and my password was 13.  After changing my password (and removing all entries in credential manager/IE -- I use git-credential-winstore which may play into that) I was able to get hub to take my credentials.

**Comment by mislav** [comment] 2015-06-03 18:55
I'm going to close this as a duplicate of #837 because they're likely caused by the same bug. I was also able to reproduce this in Windows 8.1. Follow the other ticket for updates, and thanks for reporting.

**Closed by mislav** 2015-06-03 18:55 UTC
