### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by yiweishe** [github/hub#1459] opened 2017-04-29 15:50 UTC
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x382300, 0xc420012100)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc4200ec060, 0x1b, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x5a5740, 0xc42008efa0)
	/tmp/go/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x5a5740, 0xc42008efa0, 0x7fff5fbff81c, 0x6)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420013890, 0x5a5740, 0xc42008efa0, 0x6, 0xc420077c98, 0xc42004fed8, 0x2079)
	/tmp/go/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc420013890, 0x415cb0, 0x7d5ee, 0xc4200de0c0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/private/tmp/hub-20161003-16770-1ttiwa3/hub-2.2.9/main.go:14 +0x51

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.12.2
hub version 2.2.9
```

**Comment by mislav** [comment] 2017-06-26 15:43
Thanks for reporting! Duplicate of https://github.com/github/hub/issues/1331

**Closed by mislav** 2017-06-26 15:43 UTC
