### ISSUE TITLE
Crash report - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jvican** [github/hub#1272] opened 2016-09-18 14:24 UTC
Error (runtime.errorString): `runtime error: invalid memory address or nil pointer dereference`

Stack:

```
goroutine 1 [running]:
panic(0x77e480, 0xc420014140)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/github/hub/github.(*Client).CreatePullRequest(0xc420217b50, 0xc420070880, 0xc4201c1b90, 0xc420217bb8, 0xc4201df990, 0x0)
	/tmp/go/src/github.com/github/hub/github/client.go:107 +0x1ed
github.com/github/hub/commands.pullRequest(0x99cd20, 0xc42009e090)
	/tmp/go/src/github.com/github/hub/commands/pull_request.go:214 +0xd92
github.com/github/hub/commands.(*Command).Call(0x99cd20, 0xc42009e090, 0x40b6b9, 0x7f3763)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420015730, 0x99cd20, 0xc42009e090, 0xc, 0xc420075ca8, 0x450310)
	/tmp/go/src/github.com/github/hub/commands/runner.go:93 +0x3f
github.com/github/hub/commands.(*Runner).Execute(0xc420015730, 0x811620, 0xc4200176b0, 0xc4200001a0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:85 +0x2cb
main.main()
	/build/hub/src/github-hub-7988c4b/main.go:12 +0x49

```

Runtime:

```
GOOS: linux
GOARCH: amd64
```

Version:

```
git version 2.9.3
hub version 2.2.5
```

**Comment by mislav** [comment] 2016-09-18 22:14
Duplicate of #1273

**Closed by mislav** 2016-09-18 22:14 UTC
