### ISSUE TITLE
How to use hub with custom http URL without SSL

### ISSUE THREAD

**Issue by Swoorup** [github/hub#1406] opened 2017-02-12 11:09 UTC

**Comment by vermiculus** [comment] 2017-02-12 13:51
What exactly is the problem you're running into? What's its current behavior?

It's worth noting that [the normal GitHub API can *only* be accessed over HTTPS](https://developer.github.com/v3/#schema).

**Comment by lwiechec** [comment] 2017-02-13 11:45
hi there, I _think_ I have a similar 'issue'. We are running GitHub enterprise internally, and it is running on `http://` (so, no SSL). I have configured hub to use our GitHub hostname (using git config's `hub.host` setting) but I guess hub is hardcoded to use `https://` here.

I know that HTTPS is a way to go, but for GitHub Enterprise installations, when they sometimes are on isolated networks (like in our case), there is no need for HTTPS. It would be good to have an option here, IMHO

**Comment by Swoorup** [comment] 2017-02-13 17:58
That is exactly my problem. ^

**Comment by mislav** [comment] 2017-02-14 21:51
Right now, you have to configure this manually within the `~/.config/hub` file. Find the existing config for your GHE host and add the `protocol` line:

```yml
example.com:
- user: mislav
  oauth_token: REDACTED
  protocol: http
```

**Comment by lwiechec** [comment] 2017-02-15 08:32
@mislav hmm, I thing it should be in `~/.config/hub`, not `~/.hub/config` :)

**Comment by Swoorup** [comment] 2017-02-15 10:44
@mislav I can confirm that does not work.

**Comment by mislav** [comment] 2017-02-15 12:15
@Swoorup What exactly did you try? (Please show `~/.config/hub`, which sensitive data redacted.) What command did you run next? What happened instead?

This feature was around since hub 2.2.0. It's a bit of a hassle, but it always worked. 🤔

**Comment by lwiechec** [comment] 2017-02-15 13:47
I can confirm that it works.

**Comment by Swoorup** [comment] 2017-02-15 14:18
```
github:
- user: swoorup
  oauth_token: REDACTED
  protocol: http
```

I ran the `hub issue` command on the repository whose URL is in format of `git://`. It then asked me, for my username and password. After entering it, it would take quite a while and show me errors. I could see it tried to access a https site instead.

**Comment by mislav** [comment] 2017-02-15 16:24
In the first line of what you pasted there is `github:`. Instead of that, it should be the exact name of your host where GHE is installed, in the same way it appears in the `git://HOSTNAME/...` url for your git remote. Can you double-check that it matches?

**Comment by Swoorup** [comment] 2017-02-15 16:40
Its github :) without the [dot] com

**Comment by mislav** [comment] 2017-02-15 17:28
Ah, I see. Which `hub version` do you have? What do you see when you use `HUB_VERBOSE=1 hub issue` in that repo? (Again, try to mask out sensitive data!)

**Comment by mislav** [comment] 2017-06-26 21:31
@Swoorup Did you ever manage to get this working?

**Comment by mislav** [comment] 2019-02-07 00:58
Closing due to lack of info

**Closed by mislav** 2019-02-07 00:58 UTC
Labels: unconfirmed
