### ISSUE TITLE
hub pull-request option for GitHub Projects

### ISSUE THREAD

**Issue by autarchprinceps** [github/hub#2370] opened 2019-11-22 09:52 UTC
I don't know whether I am missing something, but I don't see the option in hub pull-request to define what projects to assign said pr to.
The other options, which in the Web UI reside in the right sidebar, reviewers, assignees, milestones and even labels I do see, but not projects.

**Comment by mislav** [comment] 2019-11-22 17:14
Thank you! Closing as duplicate of https://github.com/github/hub/issues/1858

**Closed by mislav** 2019-11-22 17:14 UTC
Labels: feature
