### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by Hano1388** [github/hub#1525] opened 2017-07-31 22:01 UTC
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x382300, 0xc4200140f0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc42001aae0, 0x4f, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x5a5740, 0xc420082fa0)
	/tmp/go/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x5a5740, 0xc420082fa0, 0x7fff5fbff7b4, 0x6)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc420015880, 0x5a5740, 0xc420082fa0, 0x6, 0xc42006bca0, 0xc420055ed8, 0x2079)
	/tmp/go/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc420015880, 0x415cb0, 0x7d5ee, 0xc4200d20c0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/private/tmp/hub-20161003-16770-1ttiwa3/hub-2.2.9/main.go:14 +0x51

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.11.0 (Apple Git-81)
hub version 2.2.9
```

**Comment by mislav** [comment] 2017-08-01 14:18
Thanks for reporting! This was fixed in 01c3099abe56a8dcca41e285c11c0f6f860cc338 and will be a part of the next stable release. This is most likely caused by calling `hub` commands from **within a bare git repo**. To avoid the crash for now, please avoid running `hub` commands from a bare git repo and run them only from a normal git checkout. Thank you!

**Closed by mislav** 2017-08-01 14:18 UTC
