### ISSUE TITLE
Command Request: browse PR from commit hash

### ISSUE THREAD

**Issue by benwainwright** [github/hub#1899] opened 2018-10-13 17:12 UTC
Hi there

A very common Github workflow for me is to

- Git blame a particular line
- Grab the hash from the blame
- Search for relevant pull request for the appropriate repo
- Visit the PR page

This is so common for me that I have a [vim mapping that automates most of it](https://github.com/benwainwright/dotfiles/blob/4cd643437180f72e1edcb566a3b5b3d9565e0fac/config/vim/vimrc.dotfile#L119-L133).

I think this would be a nice feature for Hub, and if there is agreement here, I'd like to have a go at implementing it (it would be my first open source contribution). My question is, what form should it take

I thought about maybe a subcommand on `hub browse`; perhaps the following:

- `hub browse pr --containing <commit-hash>`
- `hub browse pr --containing <file>:<line-number>`

and for completeness

- `hub browse pr <pr-number>`

Of course this could equally be a subcommand on `hub pr`: 

- `hub pr browse --containing <commit-hash>`
- `hub pr browse --containing <file>:<line-number>`
- `hub pr browse <pr-number>`

Any thoughts or suggestions for alternative approaches would be much appreciated

**Comment by mislav** [comment] 2018-10-13 18:43
Thanks for a detailed outline of your feature request! This will be possible when hub supportings querying the issue/PR search interface. The implementation hasn't started yet, but I'm going to close this as a duplicate of https://github.com/github/hub/issues/1541

**Closed by mislav** 2018-10-13 18:43 UTC
