### ISSUE TITLE
Support for issue and PR templates

### ISSUE THREAD

**Issue by arnarthor** [github/hub#1123] opened 2016-02-25 13:39 UTC
Would love to have support for the PR and issues template that were announced recently.

If the repo has a template then prefill the PR and issues process with the template.

**Comment by hkdobrev** [comment] 2016-02-25 13:54
Most probably a duplicate of #1118

**Comment by mislav** [comment] 2016-02-25 14:02
Yes a duplicate, thank you @hkdobrev. @arnarthor Please follow the referenced issue for updates!

**Closed by mislav** 2016-02-25 14:02 UTC
