### ISSUE TITLE
hub spuriously requesting password

### ISSUE THREAD

**Issue by treyharris** [github/hub#1176] opened 2016-05-10 23:40 UTC
By adding my GitHub SSH key to `ssh-add`, I'm able to interact password-lessly most of the time. But sometimes, this happens:

```
$ git clone caskroom/homebrew-cask
github.com password for treyharris (never stored):
Cloning into 'homebrew-cask'...
remote: Counting objects: 199958, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 199958 (delta 2), reused 0 (delta 0), pack-reused 199951
Receiving objects: 100% (199958/199958), 59.24 MiB | 8.45 MiB/s, done.
Resolving deltas: 100% (136746/136746), done.
Checking connectivity... done.
```

When it requested a password there, I just pressed return without entering anything, yet it continued successfully.

Unfortunately, that didn't continue to be the case:

```
$ cd homebrew-cask
$ git fork
github.com password for treyharris (never stored):
Error forking repository: Unauthorized (HTTP 401)
Bad credentials
$ git remote -v
origin	git://github.com/caskroom/homebrew-cask.git (fetch)
origin	git://github.com/caskroom/homebrew-cask.git (push)
```

To demonstrate, my SSH key is valid:
```
$ ssh-add -l
2048 SHA256:Uq8lTltyyQsm5O5v0mGzTpA5Pp0wdstcO0tz3OEexJc /Users/trey/.ssh/github_rsa (RSA)
$ ssh -T git@github.com
Hi treyharris! You've successfully authenticated, but GitHub does not provide shell access.
```

And I can access private repos without a password:
```
% git clone -p treyharris/emacs.d
Cloning into 'emacs.d'...
remote: Counting objects: 3314, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 3314 (delta 506), reused 502 (delta 502), pack-reused 2806
Receiving objects: 100% (3314/3314), 3.43 MiB | 959.00 KiB/s, done.
Resolving deltas: 100% (1449/1449), done.
Checking connectivity... done.
% cd emacs.d
% git remote -v
origin	git@github.com:treyharris/emacs.d.git (fetch)
origin	git@github.com:treyharris/emacs.d.git (push)
```

**Comment by TheDoctorsLife** [comment] 2016-05-11 23:59
Git fork uses the github api endpoint, which doesn't use ssh rather it uses https and passwords.

**Comment by treyharris** [comment] 2016-05-12 16:51
@TheDoctorsLife Understood, but that doesn't explain the first password request—which I was able to just skip without entering anything.

**Comment by mislav** [comment] 2016-08-07 15:52
@treyharris Thanks for reporting, and sorry for the late reply! If you didn't enter a password when hub asked you to, or if you entered a wrong password, hub should definitely exit with an error message without continuing. That's a bug, and I'll try to fix it.

**Comment by mislav** [comment] 2016-08-07 16:47
Duplicate of https://github.com/github/hub/issues/1122

**Closed by mislav** 2016-08-07 16:47 UTC
Labels: bug
