### ISSUE TITLE
`hub pr checkout` in 'detached HEAD' state

### ISSUE THREAD

**Issue by dorian-marchal** [github/hub#2469] opened 2020-02-12 09:20 UTC
**The problem I'm trying to solve:**

I want to checkout a PR locally in order to navigate the codebase while I'm reviewing.
I don't want to keep the branch around so I  would like to checkout in 'detached HEAD' state, without creating a branch locally.

Currently, I manually check a PR out with these steps:

- *look up the last commit of the PR I want to checkout on github.com*
- Fetch the remote : `git fetch upstream`
- Checkout the commit : `git checkout <COMMIT-HASH>`

**How I imagine hub could expose this functionality:**

Maybe `hub pr checkout [--detached] <PR-NUMBER> [<BRANCH>]`

Ideally, this would **not** create the branch locally, only checkout the latest commit of the PR.

**Comment by mislav** [comment] 2020-02-21 14:25
Thank you for the suggestion! Duplicate of https://github.com/github/hub/issues/1206

**Closed by mislav** 2020-02-21 14:25 UTC
Labels: feature
