### ISSUE TITLE
hub stash [command] [stash ref] gives ambiguous argument/unknown revision error

### ISSUE THREAD

**Issue by SnoringFrog** [github/hub#1268] opened 2016-09-14 14:48 UTC
EDIT: **TLDR if you're looking for a workaround**: `hub` + `Cygwin` needs to find a Windows-installed `git` first on the `PATH`, otherwise things get treated like they were passed through the shell again and stuff breaks. Use a Windows-installed `git` or a shell function to not use `hub` when using the `stash` command.

It seems that any `stash` command that is supplied with a specific stash reference gives this error:

> fatal: ambiguous argument 'stash@0': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'

Obviously with 'stash@0' being replaced by whatever stash was specified.

Thusfar, I've confirmed this happens with `stash save`, `stash apply`, and `stash show` and `stash drop`. I haven't seen this error with non-`stash` commands. Using any of these without specifying a stash works as expected. 

I am working from Cygwin on Windows 10. `hub --version` reports: 

> git version 2.8.3
> hub version 2.3.0-pre3-3-g328df93

**Comment by mislav** [comment] 2016-09-14 15:23
Hub doesn't touch the `stash` command at all, leaving all its arguments intact.

What do you get if you instead of `hub stash show stash@{0}` do `command git stash show stash@{0}`? If it's the same result, then your problem is with git, not hub.

**Comment by SnoringFrog** [comment] 2016-09-14 16:29
`command git stash show stash@{0}` works as expected.

**Comment by mislav** [comment] 2016-09-14 18:53
I can't reproduce with Cygwin on Windows 8.1. I may have to try install Windows 10.

So the issue seems that the hub executable somehow strips away the `{}` characters from the argument, right? At first it seemed to me something like a misbehaving shell might try to do, but if you say that `command git …` approach worked, then we can rule out the shell.

What is the result of `HUB_VERBOSE=1 hub stash show stash@{0}`?

Can you try building the latest version from master?

**Comment by SnoringFrog** [comment] 2016-09-14 22:24
Right, that's what it looked like to me as well. I tried poking around the `hub`. 

`HUB_VERBOSE=1 hub stash show stash@{0}` returns:

> $ git config alias.stash
> $ git stash show stash@{0}
> fatal: ambiguous argument 'stash@0': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'

I tried building the latest master version, but the build script is currently giving me an error: `.\main.go:15: err.Ran undefined (type commands.ExecError has no field or method Ran)`. Which doesn't make any sense, because `commands/runner.go:19` seems to define the field `Ran` for type `ExecError`.

**Comment by mislav** [comment] 2016-09-14 23:24
Compiling from Cygwin works for me. That error does look weird— it might be that you have multiple versions of hub mixed up in your GOPATH, and one of them is outdated. `Ran` is a field introduced between the version that you had your original problem with and the latest version.

Also, `script/build` is a bit hackish and I wouldn't trust it to run impeccably on Windows. Try this:

1. Clone `github/hub` into your `$GOPATH/src/github.com/github/hub`
2. `cd` into that directory
3. `go build -o bin/hub.exe`
4. `bin/hub stash show stash@{0}`

**Comment by SnoringFrog** [comment] 2016-09-15 19:09
Looks like `c.Run()` is returning an error. The arguments going into it are what would be expected, so it looks like the error is not actually in `hub` itself. Guess I need to dig into how `os.exec.Run()` operates then.

**Comment by mislav** [comment] 2016-10-03 17:31
> The braces just need to be escaped in `hub`. Manually changing the final argument passed to `exec.Command` from the string `stash@{0}` to either `'stash@{0}'` or `stash@\\{0\\}` fixes the issue. The single quotes fixing the issue means there is probably some shell expansion going on in here somewhere.

That's **really** bizarre. Ordinarily, escaping or quoting is done to avoid a shell expanding certain syntaxes. However, we're not in a context of a shell when we pass on these arguments. Go should have passed them intact to the `git` executable.

I still can't explain why you are getting this issue and I am not. I can't just make the change of escaping the `{}` characters, because if I do, and they weren't necessary on a particular system, we would end up passing literal backslashes or quotes in the argument value, and then git would choke on it:

```
$ git stash show 'stash@\{0\}'
stash@\{0\} is not a valid reference
```

I'm not sure what to do here, but I suspect maybe your original issue is some faul play between Go and Cygwin. Can you try to reproduce your problem in cmd.exe, PowerShell, or git bash?

**Comment by SnoringFrog** [comment] 2016-10-03 22:54
`hub stash show stash@{0}` works fine in git bash and cmd.exe.

`hub stash show stash@{0}` fails in Powershell ("fatal: ambiguous argumend 'stash@'..."), but ``hub stash show 'stash@{0}'` works in Powershell (I haven't used Powershell a lot, this may be a expansion/parsing issue that's to be expected there, I'm not sure). 

So it is almost certainly a Cygwin/Go communication problem. I'd guess that when Go calls a `git` that's from Cygwin, the arguments get passed as if they're coming from a CLI and thus expansion happens again. If I tweak my `PATH` in Cygwin so that a native Windows `git` installation is found before one of the Cygwin-installed ones, then `hub` works as it should (until today, I didn't have `git` installed directly to Windows at all, however).

So it's definitely just another weird Cygwin thing, in the end. Not sure if it's worth working around, but might at least be worth noting in docs somewhere that a Windows-installed git is needed for all functionality on Windows because the Cygwin one won't cut it.

**Comment by mislav** [comment] 2019-02-07 00:57
Closing since this doesn't sound like a bug in hub

**Closed by mislav** 2019-02-07 00:57 UTC
Labels: unconfirmed
