### ISSUE TITLE
Can't create pull request with labels containing spaces

### ISSUE THREAD

**Issue by rohandang** [github/hub#1572] opened 2017-09-17 06:49 UTC
When attempting to create a pull request in the pre-release version `2.3.0-pre10` with labels that contain a space, I'm unable to get hub to pick up the actual label name.

E.g. using this command:
`hub pull-request  -l "do not merge"`
I end up with a label called `"do` (looks like it's picking only the first chunk before a space and ignoring the rest?)

**Comment by mislav** [comment] 2017-09-24 13:36
I cannot reproduce using 2.3.0-pre10 and this command run from bash shell:

```sh
hub pull-request -l "do not merge"
```

The label `do not merge` is correctly created and applied. This should work for you too, because in your example, you enclosed `"do not merge"` in quotes, which should have helped preserve spaces. I don't know why it didn't work. From which shell did you try to run that command?

**Comment by brianeclow** [comment] 2018-01-24 22:32
I am using 2.3.0-pre10, and `hub pull-request` keeps having an issue with an exiting label with a space. A script I am developing issues:
```
hub pull-request -l 'spaced label' -r 'person1,person2,person3,person4'
```
And it will create a label `'spaced` and apply it to the PR instead of using the existing label of `spaced label`. As an aside, hub will only add the first two reviewers.

Are the options dependent on using double quotes over single quotes?

**Comment by brianeclow** [comment] 2018-01-24 23:03
Confirmed, I am getting the same results using either double or single quotes around the label.

**Comment by brianeclow** [comment] 2018-01-24 23:14
I switched the order of the arguments, just for giggles, and I still had the same results.

**Comment by brianeclow** [comment] 2018-01-26 18:36
I also tried without quotes as the last argument. This time it created the label `spaced` instead of `spaced label`.

My environment:
macOS: `10.12.6`
hub: `2.3.0-pre10`
git: `2.16.1`
bash: `3.2.57(1)-release (x86_64-apple-darwin16)`
script's `#!`: `#!/bin/bash`, which is the referenced system version

**Comment by brianeclow** [comment] 2018-01-26 20:59
Alright, I ran the command that is generated by the script naked on the CLI, and it was able to set the label correctly. I am guessing, hub is having issues dealing with shell quoting. The command I ran is as follows:
```
hub pull-request -F PR_COMMENT -r person1,person2,person3,person4 -a brianeclow -l "spaced label"
```
It should be noted, that I figured out why requesters was not being set, that flag does not account for its arguments being quoted. It expects them unquoted.

**Comment by mislav** [comment] 2018-01-29 21:21
You've never shared your script which generates the `hub pull-request` command, so I can't verify whether you've done it correctly or not. Until your last few comments, I had assumed that you were constructing and running the `hub pull-request` command manually in bash. In bash syntax, all of the following invocations are equivalent:

```sh
hub pull-request -r p1,p2,p3 -l "spaced label"
hub pull-request -r 'p1,p2,p3' -l 'spaced label'
hub pull-request -r p1,p2,p3 -l spaced\ label
```

In short, bash doesn't care whether you're using single or double quotes (unless you're using special characters in double quotes, such as escape sequences or `$`-prefixed expressions), and only requires use of quotes when a value passed to a command-line flag contains spaces. Alternatively, you can escape spaces with a backslash if you don't want to quote the whole value.

None of this applies if you're constructing the `hub pull-request` command programatically using a script. When doing that, passing arguments and values around safely doesn't depend on your quoting style, but on whether you are knowledge enough to construct such a script.

Closing because this is not a bug with hub.

**Closed by mislav** 2018-01-29 21:21 UTC
Labels: unconfirmed

**Comment by brianeclow** [comment] 2018-01-29 21:46
This is a quick digest of the script:

```
#!/bin/bash

# collect repo root and branch info

PR_COMMENT_FILE="${ROOT}/PR_COMMENT_${BRANCH_NAME//\//_}.txt"
PR_LABEL='spaced label'
PR_REVIEWERS='p1,p2,p3,p4'
GITHUB_USERNAME='myuser'

HUB_OPTIONS="-r ${PR_REVIEWERS} -a ${GITHUB_USERNAME} -l '${PR_LABEL}'"

# git add, commit, push
hub pull-request -F ${PR_COMMENT_FILE} ${HUB_OPTIONS}
```

In this context, reviewers does care if quotes exists.
And based on your last comment, I will attempt to escape the space on the label.

**Comment by mislav** [comment] 2018-01-30 11:00
If you use bash arrays, you can stack values for labels/assignees programatically and forward them to hub without having to deal with quoting or escapes:

```sh
reviewers=()
assignees=("$GITHUB_USERNAME")
labels=()

labels+=("spaced label" "another label")
reviewers+=(person1)
reviewers+=(person2)

IFS=','
hub pull-request -F "$PR_COMMENT_FILE" -a "${assignees[*]}" -l "${labels[*]}" -r "${reviewers[*]}"
```

**Comment by brianeclow** [comment] 2018-01-30 19:46
Do'h! You are right. I always forget you can do that in bash.
