### ISSUE TITLE
`hub fork --help` unexpected behaviour

### ISSUE THREAD

**Issue by nicolaiskogheim** [github/hub#1214] opened 2016-07-21 07:43 UTC
I'm new to `hub`, and trying to fork a repo left me somewhat perplexed. You'll see what I mean.

```sh
$ git clone git@github.com:github/hub.git                                                
Cloning into 'hub'...
// ...

$ cd hub                                                                                 

$ git fork nicolaiskogheim/hub
Enter your github username
nicolaiskogheim
Enter host password for user 'nicolaiskogheim':
{
  "message": "Must specify two-factor authentication OTP code.",
  "documentation_url": "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}
Cloning into 'hub'...		# <---- wat
Username for 'https://github.com': ^C

$ hub fork --help                                                                                                                                                 git:(master)
Updating nicolaiskogheim
From ssh://github.com/github/hub
 * [new branch]      1.11-stable -> nicolaiskogheim/1.11-stable
 * [new branch]      1.12-stable -> nicolaiskogheim/1.12-stable
 * [new branch]      2.2-stable -> nicolaiskogheim/2.2-stable
 * [new branch]      gh-pages   -> nicolaiskogheim/gh-pages
 * [new branch]      master     -> nicolaiskogheim/master
 * [new branch]      revamp-issues -> nicolaiskogheim/revamp-issues
new remote: nicolaiskogheim
```

- `fork` says it fails even though it worked

- `hub fork --help` did not show help, but instead of erroring on an unsupported option, it did something else.

The repository was forked to my user.

**Comment by mislav** [comment] 2016-08-07 15:46
Sorry for the trouble! Can you try with hub 2.2.3? I'm pretty sure those bugs have already been fixed.

**Comment by mislav** [comment] 2016-08-07 17:17
I can't reproduce this with hub 2.2.3, so I'm assuming this has been fixed in a recent release. If you still have problems using hub 2.2.3, please reopen! Thanks

**Closed by mislav** 2016-08-07 17:17 UTC
Labels: unconfirmed

**Comment by nicolaiskogheim** [comment] 2016-08-07 19:56
>  I'm pretty sure those bugs have already been fixed.

Ah, yes. I didn't check that I had the latest version, sorry. I only knew I used the latest one available on `brew`. Or, at least i *thought* i did, ref #1222.

I cannot reproduce with 2.2.3. Thanks for your feedback.
