### ISSUE TITLE
Crash report - runtime error: index out of range

### ISSUE THREAD

**Issue by deadlyicon** [github/hub#1330] opened 2016-11-05 00:32 UTC
Error (runtime.errorString): `runtime error: index out of range`

Stack:

```
goroutine 1 [running]:
panic(0x382280, 0xc420010130)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/github/hub/git.WorkdirName(0xc4200e6540, 0x28, 0x0, 0x0)
	/tmp/go/src/github.com/github/hub/git/git.go:70 +0xb6
github.com/github/hub/commands.create(0x5a5740, 0xc420092fa0)
	/tmp/go/src/github.com/github/hub/commands/create.go:66 +0x6a
github.com/github/hub/commands.(*Command).Call(0x5a5740, 0xc420092fa0, 0x7fff5fbff55c, 0x6)
	/tmp/go/src/github.com/github/hub/commands/commands.go:47 +0x91
github.com/github/hub/commands.(*Runner).Call(0xc4200118c0, 0x5a5740, 0xc420092fa0, 0x6, 0xc4200de680, 0xc420055ed8, 0x2079)
	/tmp/go/src/github.com/github/hub/commands/runner.go:108 +0x39
github.com/github/hub/commands.(*Runner).Execute(0xc4200118c0, 0x415c30, 0x7d5ee, 0xc4200e40c0, 0x0)
	/tmp/go/src/github.com/github/hub/commands/runner.go:96 +0x1e9
main.main()
	/private/tmp/hub-20160912-40594-1n8dwaa/hub-2.2.8/main.go:14 +0x51

```

Runtime:

```
GOOS: darwin
GOARCH: amd64
```

Version:

```
git version 2.10.0
hub version 2.2.8
```

**Comment by mislav** [comment] 2016-11-05 10:23
Duplicate of #1331

**Closed by mislav** 2016-11-05 10:23 UTC
