### ISSUE TITLE
hub doesn't ask for 2FA code, Unauthorized (HTTP 401)

### ISSUE THREAD

**Issue by jay** [github/hub#2310] opened 2019-10-14 07:40 UTC
I'm using v2.12.8 in Windows. When I enter my username and password it tells me invalid credentials. I am sure I'm entering it correctly. I read that [hub should ask me](https://github.com/github/hub/issues/965#issuecomment-126527025) for my 2FA but it doesn't. After reading #2276 I tried GITHUB_USER and GITHUB_PASSWORD and they are correct but the reply is still 401. I've tried `pull-request` and `pr` so far.

~~~
$ HUB_VERBOSE=1 hub pr list
$ git rev-parse -q --git-dir
$ git remote -v
$ git config --get-all hub.host
> GET https://api.github.com/user
> Authorization: token [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
< HTTP 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
> POST https://api.github.com/authorizations
> Authorization: Basic [REDACTED]
> Accept: application/vnd.github.v3+json;charset=utf-8
{"note":"hub for xxxxxxxxxxxxxxxxxx","note_url":"https://hub.github.com/","scopes":["repo"]}
< HTTP 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
Bad credentials
~~~

A long time ago I had an old version of hub that worked fine. I checked and I don't have any oauth token for it listed on my github account, and I removed the ~/.config/hub file before trying all this.

**Comment by mislav** [comment] 2019-10-14 09:54
Thanks for reporting. Which terminal emulator are you using on Windows?

Even with HUB_VERBOSE debugging, hub never prints out what credentials are actually being sent to the server (this is to avoid people accidentally copy-pasting it into issues). So one thing you could try is install Go on your system and cloning hub source code and sprinkling some `Printf` statements in this area https://github.com/github/hub/blob/afdd78510c0a39389c9c5fecd9823d7438cd032b/github/config.go#L116-L125

It's possible that we are reading your password input wrong (maybe there's an extra trailing newline or such). However, it's puzzling to me that you've also tried the GITHUB_PASSWORD variable and that hasn't worked either. 🤔

**Comment by jay** [comment] 2019-10-15 07:33
I tried it with curl and the server returns 401 but without a X-GitHub-OTP header. I e-mailed github support to find out what's going on.

**Comment by mislav** [comment] 2019-11-06 13:20
@jay I'm sorry you are still blocked from authorizing with GitHub API. I have checked and your support request is being tracked & investigated, but so far there are no leads.

I'm not a support person, but I would try several approaches while you wait:
1. Change your GitHub password (sorry if this is an inconvenience),
2. Disable & reenable 2FA in your account,
3. (Hub-specific) go to https://github.com/settings/tokens and generate a Personal Access Token, then paste it into:

   ```yaml
   ---
   github.com:
   - user: jay
     oauth_token: YOUR_PAT
   ```

**Comment by mislav** [comment] 2019-11-06 13:24
Closing this since it's being handled by Support and is not a bug with hub.

**Closed by mislav** 2019-11-06 13:24 UTC
Labels: more-info-needed

**Comment by jay** [comment] 2019-11-25 05:23
> 3\. (Hub-specific workaround) go to https://github.com/settings/tokens and generate a Personal Access Token, then paste it into `~/.config/hub`

My github support ticket is still unresolved so I've followed your advice and created a token with 'repo' privileges and that seems to be working so far. Thanks.

**Comment by kissu** [comment] 2022-05-03 16:44
Damn, I always forget this file! Wish we had a `login` command (for a click auth) or a reminder that this configuration file exists. 😩
