### ISSUE TITLE
Windows newlines are handled incorrectly

### ISSUE THREAD

**Issue by rschmitt** [github/hub#920] opened 2015-06-04 02:26 UTC
Steps to reproduce:

```
git clone https://github.com/cbeust/testng
cd testng
git reset --hard ad662c0a3971e0461a1aaa7580fd3c7e7a114a02
hub am -3 https://github.com/cbeust/testng/commit/798f649b51331f2cc899b32acba29d32b7bcdc0e.patch
```

Applying the patch fails. Let's prove that newlines are the issue:
```
hub am --abort
dos2unix src/main/java/org/testng/internal/BaseTestMethod.java
git commit -am asdf
hub am -3 https://github.com/cbeust/testng/commit/798f649b51331f2cc899b32acba29d32b7bcdc0e.patch
```

**Comment by mislav** [comment] 2015-06-04 11:08
What type of newlines does "testng" have originally? What type of newlines does it have after cloning?

Do you think this is a hub issue? Does the same issue persist if you skip hub and apply the patch by downloading it manually and piping it to `git am`?

**Comment by rschmitt** [comment] 2015-06-04 15:18
The file in question is committed with Windows newlines.

I think that the bug is specifically in `git am`. For example, `git apply` works:
```
~/temp/testng # git apply <(curl -s https://github.com/rschmitt/testng/commit/d7aa93fe6e097ba15d10217bd929896d9e8a5b9c.patch)
/dev/fd/11:35: trailing whitespace.
        if (!m.contains(".")) {
warning: 1 line adds whitespace errors.
```
As does `hub apply`:
```
~/temp/testng # hub apply https://github.com/rschmitt/testng/commit/d7aa93fe6e097ba15d10217bd929896d9e8a5b9c
/var/folders/s2/646znsnr8xl_bl008k8z72ch0000gp/T/hub446436271:35: trailing whitespace.
        if (!m.contains(".")) {
warning: 1 line adds whitespace errors.
```
But `git am` seems to blow away the "trailing whitespace":
```
~/temp/testng # wget -q https://github.com/cbeust/testng/commit/d7aa93fe6e097ba15d10217bd929896d9e8a5b9c.patch

~/temp/testng # cat -vet d7aa93fe6e097ba15d10217bd929896d9e8a5b9c.patch | grep -c '\^M\$$'
8

~/temp/testng # git am -3 d7aa93fe6e097ba15d10217bd929896d9e8a5b9c.patch
Applying: Replace indexOf() with contains()
Using index info to reconstruct a base tree...
error: patch failed: src/main/java/org/testng/internal/BaseTestMethod.java:470
error: src/main/java/org/testng/internal/BaseTestMethod.java: patch does not apply
Did you hand edit your patch?
It does not apply to blobs recorded in its index.
Cannot fall back to three-way merge.
Patch failed at 0001 Replace indexOf() with contains()
The copy of the patch that failed is found in:
   /Users/rschmitt/temp/testng/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

~/temp/testng # cat -vet /Users/rschmitt/temp/testng/.git/rebase-apply/patch | grep -c '\^M\$$'
0
```

**Comment by mislav** [comment] 2015-06-05 02:39
If the problem exists with regular `git am`, then this isn't a bug with hub, right? I'm tempted to close this as something that the user has to deal with themselves. There are configuration options in git to normalize whitespace between teams that might be working on different platforms and editor configurations.

**Comment by rschmitt** [comment] 2015-06-05 03:03
Agreed, but it's a difficult problem to root cause. Anyone who tries this casually will encounter a Bug In Hub. It's up to you if you want to hand this off to someone well-versed in git internals and/or git configuration for further investigation.

**Comment by mislav** [comment] 2015-06-05 09:05
It would be great if this Just Worked™, but I don't know what causes the problem in the first place and whether there's something we can do about this in hub.

**Comment by svnpenn** [comment] 2015-06-21 21:01
I think the problem is in how hub reads and prints line endings. As a native Windows program, the Windows version of hub should be printing CRLF endings rather than the current LF found on the Windows 2.2.1 version

**Comment by svnpenn** [comment] 2015-06-21 21:01
@mislav I think the problem is in how hub reads and prints line endings. As a native Windows program, the Windows version of hub should be printing CRLF endings rather than the current LF found on the Windows 2.2.1 version

**Comment by mislav** [comment] 2015-06-22 04:07
@svnpenn I'm not convinced. Where should we be outputting CRLF— to standard output? I don't know how that would help `git am`.

What I'd like here is to be able to understand completely which program chokes (hub or git itself) and on which exact input.

**Comment by svnpenn** [comment] 2015-06-22 04:25
@mislav I dont have to convince you. Windows has been using CRLF
[since the 80s][1]. If you cant see how dumping a 30 year convention might cause
problems, then this issue might be beyond your help.

[1]:http://wikipedia.org/wiki/Newline#History

**Comment by rschmitt** [comment] 2015-06-22 04:38
@svnpenn Did you not see my comments above? I presented pretty good evidence that the problem is somewhere in `git am`. I also have been unable to find any issues with how github formats patches, or how hub applies individual patches. It's not like hub is stripping carriage returns in diffs.

**Comment by mislav** [comment] 2016-01-22 11:55
Since the but is in `git am` proper, like @rschmitt demonstrated, there's little we can do about that from within hub. However, if someone has an idea for a fix, please add your comments here. In the meantime, I'm closing this issue as not a bug with hub per se.

**Closed by mislav** 2016-01-22 11:55 UTC
Labels: ¯\_(ツ)_/¯
