### ISSUE TITLE
Terminal PR template loses heading style after submitting  

### ISSUE THREAD

**Issue by ak077** [github/hub#1918] opened 2018-10-25 20:27 UTC
When I try to create PR from terminal without mentioning file name, it will pick up default PR template but after submitting it loses heading styles.

```bash 
hub pull-request 
```
opens up pull request default template for project as below 

```
### Description 
Lorem ipsum
- [ ] Checklist 1
```
will result as below on github.

Lorem ipsum
- [ ] Checklist 1

**Comment by salmanulfarzy** [comment] 2018-10-26 09:50
Duplicate of #1377 ? PR at #1916.

**Comment by mislav** [comment] 2018-10-26 11:42
Thank you @salmanulfarzy!

**Closed by mislav** 2018-10-26 11:42 UTC
